// Generated by Framer (6b748fa)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion } from "framer-motion";
import * as React from "react";
import Ticker from "https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/XVUmpmPn1EPL0dzocT35/Ticker.js";
import {
  Language_Chn_Content,
  Language_En_Content,
  Toggle_Layout,
} from "https://framerusercontent.com/modules/yue1wEIuxL5Wxj17VKpu/rvoe6u8OOiWRrmZZxev9/Toggle.js";
import * as sharedStyle from "https://framerusercontent.com/modules/NTzdpmdGzV4l1oiX0egj/kZYaUGhJWNS3YMbZ9hot/xFx_9r8NJ.js";
const RichTextLanguage_En_Content = Language_En_Content(RichText);
const RichTextLanguage_Chn_Content = Language_Chn_Content(RichText);
const TickerFonts = getFonts(Ticker);
const MotionDivToggle_Layout = Toggle_Layout(motion.div);
const cycleOrder = ["Tc5rzSAMC"];
const serializationHash = "framer-3qD2W";
const variantClassNames = { Tc5rzSAMC: "framer-v-1g21gpf" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const Variants = motion(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Tc5rzSAMC",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [sharedStyle.className];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(motion.div, {
        ...restProps,
        ...gestureHandlers,
        className: cx(
          serializationHash,
          ...sharedStyleClassNames,
          "framer-1g21gpf",
          className,
          classNames,
        ),
        "data-framer-name": "Desktop",
        layoutDependency: layoutDependency,
        layoutId: "Tc5rzSAMC",
        ref: ref !== null && ref !== void 0 ? ref : ref1,
        style: {
          borderBottomLeftRadius: 50,
          borderBottomRightRadius: 50,
          borderTopLeftRadius: 50,
          borderTopRightRadius: 50,
          ...style,
        },
        children: /*#__PURE__*/ _jsxs(MotionDivToggle_Layout, {
          className: "framer-1wsp1zt",
          layoutDependency: layoutDependency,
          layoutId: "IArmCftNA",
          style: {
            backgroundColor:
              "var(--token-06c3110c-0775-4f83-beaa-2e83a6a2d842, rgb(0, 0, 0))",
            borderBottomLeftRadius: 50,
            borderBottomRightRadius: 50,
            borderTopLeftRadius: 50,
            borderTopRightRadius: 50,
          },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-f5mbrb-container",
                layoutDependency: layoutDependency,
                layoutId: "GV0yIbynm-container",
                children: /*#__PURE__*/ _jsx(Ticker, {
                  alignment: "center",
                  direction: "left",
                  fadeOptions: {
                    fadeAlpha: 0,
                    fadeContent: true,
                    fadeInset: 0,
                    fadeWidth: 25,
                    overflow: false,
                  },
                  gap: 10,
                  height: "100%",
                  hoverFactor: 0.5,
                  id: "GV0yIbynm",
                  layoutId: "GV0yIbynm",
                  padding: 10,
                  paddingBottom: 10,
                  paddingLeft: 10,
                  paddingPerSide: false,
                  paddingRight: 10,
                  paddingTop: 10,
                  sizingOptions: { heightType: true, widthType: true },
                  slots: [
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-9rziyk",
                      layoutDependency: layoutDependency,
                      layoutId: "B9w8U9iBN",
                      children: [
                        /*#__PURE__*/ _jsx(RichTextLanguage_En_Content, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h4, {
                              className: "framer-styles-preset-1w7o0dx",
                              "data-styles-preset": "xFx_9r8NJ",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-1eung3n, rgb(255, 255, 255))",
                              },
                              children: "✦ Get immersed",
                            }),
                          }),
                          className: "framer-1pzpeou",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "h3qQTJJjs",
                          style: {
                            "--extracted-1eung3n": "rgb(255, 255, 255)",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichTextLanguage_Chn_Content, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h4, {
                              className: "framer-styles-preset-1w7o0dx",
                              "data-styles-preset": "xFx_9r8NJ",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-1eung3n, rgb(255, 255, 255))",
                              },
                              children: "✦ 沉浸其中",
                            }),
                          }),
                          className: "framer-495i07",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "NQQcwITHn",
                          style: {
                            "--extracted-1eung3n": "rgb(255, 255, 255)",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  ],
                  speed: 50,
                  style: { height: "100%", width: "100%" },
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1idgvyo",
              layoutDependency: layoutDependency,
              layoutId: "fqNGB7wGi",
              style: {
                background:
                  'linear-gradient(90deg, var(--token-06c3110c-0775-4f83-beaa-2e83a6a2d842, rgb(0, 0, 0)) /* {"name":"Dark 100"} */ 49.58239489489488%, var(--token-50dd0df5-e960-4a6c-8af2-3b7603ba51c8, rgba(0, 0, 0, 0)) /* {"name":"Black 0"} */ 100%)',
              },
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1iuql2w",
              layoutDependency: layoutDependency,
              layoutId: "qdw7aKq5c",
              style: {
                background:
                  'linear-gradient(270deg, var(--token-06c3110c-0775-4f83-beaa-2e83a6a2d842, rgb(0, 0, 0)) /* {"name":"Dark 100"} */ 49.58239489489488%, var(--token-50dd0df5-e960-4a6c-8af2-3b7603ba51c8, rgba(0, 0, 0, 0)) /* {"name":"Black 0"} */ 100%)',
              },
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-3qD2W.framer-1a7id9, .framer-3qD2W .framer-1a7id9 { display: block; }",
  ".framer-3qD2W.framer-1g21gpf { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-3qD2W .framer-1wsp1zt { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 24px; position: relative; width: 226px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-3qD2W .framer-f5mbrb-container { flex: none; height: 30px; position: relative; width: 170px; }",
  ".framer-3qD2W .framer-9rziyk { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-3qD2W .framer-1pzpeou, .framer-3qD2W .framer-495i07 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-3qD2W .framer-1idgvyo { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; top: 0px; width: 52px; z-index: 1; }",
  ".framer-3qD2W .framer-1iuql2w { bottom: 0px; flex: none; overflow: hidden; position: absolute; right: 0px; top: 0px; width: 52px; z-index: 1; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3qD2W.framer-1g21gpf, .framer-3qD2W .framer-1wsp1zt, .framer-3qD2W .framer-9rziyk { gap: 0px; } .framer-3qD2W.framer-1g21gpf > *, .framer-3qD2W .framer-1wsp1zt > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-3qD2W.framer-1g21gpf > :first-child, .framer-3qD2W .framer-1wsp1zt > :first-child { margin-top: 0px; } .framer-3qD2W.framer-1g21gpf > :last-child, .framer-3qD2W .framer-1wsp1zt > :last-child { margin-bottom: 0px; } .framer-3qD2W .framer-9rziyk > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-3qD2W .framer-9rziyk > :first-child { margin-left: 0px; } .framer-3qD2W .framer-9rziyk > :last-child { margin-right: 0px; } }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 78
 * @framerIntrinsicWidth 226
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerB4XiJi4Cl = withCSS(Component, css, "framer-3qD2W");
export default FramerB4XiJi4Cl;
FramerB4XiJi4Cl.displayName = "Home/Immersed";
FramerB4XiJi4Cl.defaultProps = { height: 78, width: 226 };
addFonts(
  FramerB4XiJi4Cl,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
          weight: "400",
        },
      ],
    },
    ...TickerFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerB4XiJi4Cl",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}',
        framerIntrinsicHeight: "78",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "226",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
