// Generated by Framer (6b748fa)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const cycleOrder = [
  "h8a_pZJCm",
  "NFj1vp7St",
  "X5XFaT1T0",
  "v_V6Q3Udx",
  "ekaJDNXT2",
  "e2HhRmGaA",
  "Gguwbuzjf",
  "JYHBin7ud",
];
const serializationHash = "framer-bSX6l";
const variantClassNames = {
  e2HhRmGaA: "framer-v-1dmnua9",
  ekaJDNXT2: "framer-v-13se6hj",
  Gguwbuzjf: "framer-v-18w6533",
  h8a_pZJCm: "framer-v-57w426",
  JYHBin7ud: "framer-v-1p5cfew",
  NFj1vp7St: "framer-v-1x3hveh",
  v_V6Q3Udx: "framer-v-1k0ntq",
  X5XFaT1T0: "framer-v-5w90xr",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 28,
  delay: 0,
  mass: 1,
  stiffness: 178,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
  Desktop_Initial: "X5XFaT1T0",
  Desktop_Show: "v_V6Q3Udx",
  Monitor_Initial: "h8a_pZJCm",
  Monitor_Show: "NFj1vp7St",
  Phone_Initial: "Gguwbuzjf",
  Phone_Show: "JYHBin7ud",
  Tablet_Initial: "ekaJDNXT2",
  Tablet_Show: "e2HhRmGaA",
};
const getProps = ({ height, id, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    variant:
      (_ref =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref !== void 0
        ? _ref
        : "h8a_pZJCm",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "h8a_pZJCm",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onAppearabdpmv = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("NFj1vp7St"), 1500);
  });
  const onAppear1gacq99 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("v_V6Q3Udx"), 1500);
  });
  const onAppearslzzii = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("e2HhRmGaA"), 1500);
  });
  const onAppearpxh8r8 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("JYHBin7ud"), 1500);
  });
  useOnVariantChange(baseVariant, {
    default: onAppearabdpmv,
    e2HhRmGaA: undefined,
    ekaJDNXT2: onAppearslzzii,
    Gguwbuzjf: onAppearpxh8r8,
    JYHBin7ud: undefined,
    v_V6Q3Udx: undefined,
    X5XFaT1T0: onAppear1gacq99,
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-57w426",
            className,
            classNames,
          ),
          "data-framer-name": "Monitor_Initial",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "h8a_pZJCm",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style },
          ...addPropertyOverrides(
            {
              e2HhRmGaA: {
                "data-framer-name": "Tablet_Show",
                "data-highlight": undefined,
              },
              ekaJDNXT2: { "data-framer-name": "Tablet_Initial" },
              Gguwbuzjf: { "data-framer-name": "Phone_Initial" },
              JYHBin7ud: {
                "data-framer-name": "Phone_Show",
                "data-highlight": undefined,
              },
              NFj1vp7St: { "data-framer-name": "Monitor_Show" },
              v_V6Q3Udx: {
                "data-framer-name": "Desktop_Show",
                "data-highlight": undefined,
              },
              X5XFaT1T0: { "data-framer-name": "Desktop_Initial" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsx(motion.div, {
            className: "framer-kdvm8l",
            "data-framer-name": "Cover",
            layoutDependency: layoutDependency,
            layoutId: "HStqakslQ",
            style: {
              borderBottomLeftRadius: 50,
              borderBottomRightRadius: 50,
              borderTopLeftRadius: 50,
              borderTopRightRadius: 50,
            },
            children: /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1bivklo",
              layoutDependency: layoutDependency,
              layoutId: "Dnr3PiQad",
              style: {
                backgroundColor:
                  "var(--token-06c3110c-0775-4f83-beaa-2e83a6a2d842, rgb(0, 0, 0))",
                borderBottomLeftRadius: 53,
                borderBottomRightRadius: 53,
                borderTopLeftRadius: 53,
                borderTopRightRadius: 53,
              },
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1i0me3a",
                layoutDependency: layoutDependency,
                layoutId: "biyDJ158s",
                children: /*#__PURE__*/ _jsx(SVG, {
                  className: "framer-1h39rvi",
                  "data-framer-name": "graphic",
                  layout: "position",
                  layoutDependency: layoutDependency,
                  layoutId: "dwHfk6UP1",
                  opacity: 1,
                  svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 56 56"><path d="M 42.128 23.464 C 43.745 21.824 46.117 21.177 48.342 21.767 C 50.568 22.358 52.307 24.096 52.898 26.321 C 53.49 28.547 52.844 30.918 51.205 32.536 C 48.699 35.042 44.636 35.043 42.129 32.537 C 39.623 30.031 39.623 25.968 42.128 23.462 Z M 12.087 24.535 C 14.868 23.182 18.275 24.124 19.903 26.763 L 22.288 30.625 C 22.596 31.122 22.778 31.416 22.925 31.621 C 22.995 31.717 23.193 31.862 23.408 31.67 C 23.604 31.507 23.854 31.264 24.276 30.854 C 26.948 28.257 31.388 28.67 33.5 31.75 L 35.369 34.475 C 36.705 36.414 37.096 38.853 36.433 41.113 L 35.887 42.971 C 35.243 45.133 33.717 46.923 31.684 47.901 L 22.724 52.255 C 20.033 53.561 16.847 53.318 14.385 51.618 L 6.347 46.041 C 3.49 44.086 2.247 40.494 3.283 37.191 L 5.383 30.548 C 6.055 28.453 7.558 26.726 9.541 25.772 L 12.089 24.535 Z" fill="rgb(255, 255, 255)"></path><path d="M 36.633 3.565 C 37.056 3.977 37.295 4.543 37.295 5.133 C 37.295 5.724 37.056 6.289 36.633 6.701 L 34.377 8.918 C 33.49 9.783 32.075 9.783 31.187 8.918 C 30.765 8.506 30.527 7.941 30.527 7.351 C 30.527 6.761 30.765 6.196 31.187 5.784 L 33.444 3.568 C 34.331 2.702 35.746 2.702 36.633 3.568 Z M 52.423 3.568 C 52.846 3.98 53.085 4.545 53.085 5.136 C 53.085 5.726 52.846 6.292 52.423 6.704 L 34.377 24.435 C 33.49 25.3 32.075 25.3 31.187 24.435 C 30.764 24.023 30.526 23.457 30.526 22.867 C 30.526 22.276 30.764 21.711 31.187 21.299 L 49.233 3.57 C 50.121 2.705 51.536 2.705 52.423 3.57 Z M 29.867 10.215 C 30.289 10.627 30.527 11.192 30.527 11.782 C 30.527 12.372 30.289 12.937 29.867 13.349 L 23.1 19.999 C 22.213 20.864 20.798 20.864 19.91 19.999 C 19.488 19.587 19.25 19.022 19.25 18.432 C 19.25 17.842 19.488 17.277 19.91 16.865 L 26.677 10.215 C 27.564 9.35 28.979 9.35 29.867 10.215 Z" fill="rgb(255, 255, 255)"></path></svg>',
                  svgContentId: 12850868960,
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      e2HhRmGaA: {
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 34"><path d="M 25.578 14.246 C 26.56 13.251 27.999 12.857 29.351 13.216 C 30.702 13.574 31.758 14.63 32.117 15.981 C 32.476 17.332 32.084 18.772 31.089 19.754 C 29.567 21.276 27.1 21.276 25.579 19.755 C 24.057 18.233 24.057 15.766 25.578 14.245 Z M 7.338 14.896 C 9.027 14.075 11.095 14.647 12.084 16.249 L 13.532 18.594 C 13.719 18.896 13.829 19.074 13.919 19.199 C 13.961 19.257 14.082 19.345 14.212 19.228 C 14.331 19.129 14.483 18.982 14.739 18.733 C 16.361 17.156 19.057 17.407 20.339 19.277 L 21.474 20.931 C 22.285 22.109 22.523 23.589 22.12 24.962 L 21.788 26.089 C 21.397 27.402 20.471 28.489 19.237 29.083 L 13.797 31.726 C 12.163 32.519 10.228 32.372 8.734 31.34 L 3.853 27.954 C 2.119 26.766 1.364 24.586 1.993 22.58 L 3.268 18.547 C 3.676 17.275 4.589 16.226 5.793 15.647 L 7.34 14.896 Z" fill="rgb(255, 255, 255)"></path><path d="M 22.242 2.165 C 22.499 2.415 22.643 2.758 22.643 3.117 C 22.643 3.475 22.499 3.819 22.242 4.069 L 20.872 5.415 C 20.333 5.94 19.474 5.94 18.935 5.415 C 18.679 5.164 18.534 4.821 18.534 4.463 C 18.534 4.105 18.679 3.762 18.935 3.512 L 20.305 2.166 C 20.844 1.641 21.703 1.641 22.242 2.166 Z M 31.828 2.166 C 32.085 2.416 32.23 2.76 32.23 3.118 C 32.23 3.477 32.085 3.82 31.828 4.07 L 20.872 14.835 C 20.333 15.361 19.474 15.361 18.935 14.835 C 18.678 14.585 18.533 14.242 18.533 13.883 C 18.533 13.525 18.678 13.181 18.935 12.931 L 29.892 2.168 C 30.43 1.642 31.29 1.642 31.828 2.168 Z M 18.133 6.202 C 18.39 6.452 18.534 6.795 18.534 7.153 C 18.534 7.512 18.39 7.855 18.133 8.105 L 14.025 12.142 C 13.486 12.668 12.627 12.668 12.088 12.142 C 11.832 11.892 11.687 11.549 11.687 11.191 C 11.687 10.833 11.832 10.49 12.088 10.24 L 16.197 6.202 C 16.735 5.677 17.595 5.677 18.133 6.202 Z" fill="rgb(255, 255, 255)"></path></svg>',
                        svgContentId: 9217798269,
                      },
                      JYHBin7ud: {
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 22 22"><path d="M 16.55 9.218 C 17.186 8.574 18.117 8.32 18.992 8.552 C 19.866 8.783 20.549 9.466 20.781 10.34 C 21.014 11.215 20.76 12.146 20.116 12.782 C 19.132 13.767 17.536 13.767 16.551 12.782 C 15.566 11.798 15.566 10.202 16.55 9.217 Z M 4.748 9.639 C 5.841 9.107 7.179 9.477 7.819 10.514 L 8.756 12.031 C 8.877 12.227 8.948 12.342 9.006 12.423 C 9.034 12.46 9.112 12.517 9.196 12.442 C 9.273 12.378 9.371 12.282 9.537 12.121 C 10.587 11.101 12.331 11.263 13.161 12.473 L 13.895 13.544 C 14.42 14.306 14.574 15.264 14.313 16.152 L 14.098 16.881 C 13.845 17.731 13.246 18.434 12.447 18.818 L 8.927 20.529 C 7.87 21.042 6.618 20.946 5.651 20.279 L 2.493 18.088 C 1.371 17.319 0.883 15.908 1.29 14.611 L 2.115 12.001 C 2.379 11.178 2.969 10.499 3.748 10.125 L 4.749 9.639 Z" fill="rgb(255, 255, 255)"></path><path d="M 14.392 1.401 C 14.558 1.563 14.652 1.785 14.652 2.017 C 14.652 2.249 14.558 2.471 14.392 2.633 L 13.505 3.504 C 13.157 3.843 12.601 3.843 12.252 3.504 C 12.086 3.342 11.993 3.12 11.993 2.888 C 11.993 2.656 12.086 2.434 12.252 2.272 L 13.139 1.402 C 13.487 1.062 14.043 1.062 14.392 1.402 Z M 20.595 1.402 C 20.761 1.563 20.855 1.786 20.855 2.018 C 20.855 2.25 20.761 2.472 20.595 2.634 L 13.505 9.599 C 13.157 9.939 12.601 9.939 12.252 9.599 C 12.086 9.437 11.992 9.215 11.992 8.983 C 11.992 8.751 12.086 8.529 12.252 8.367 L 19.342 1.403 C 19.69 1.063 20.246 1.063 20.595 1.403 Z M 11.733 4.013 C 11.899 4.175 11.993 4.397 11.993 4.629 C 11.993 4.86 11.899 5.082 11.733 5.244 L 9.075 7.857 C 8.726 8.197 8.17 8.197 7.822 7.857 C 7.656 7.695 7.562 7.473 7.562 7.241 C 7.562 7.009 7.656 6.787 7.822 6.626 L 10.48 4.013 C 10.829 3.673 11.385 3.673 11.733 4.013 Z" fill="rgb(255, 255, 255)"></path></svg>',
                        svgContentId: 11810255475,
                      },
                      v_V6Q3Udx: {
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 44 44"><path d="M 33.101 18.436 C 34.371 17.148 36.235 16.639 37.983 17.103 C 39.732 17.567 41.098 18.932 41.563 20.681 C 42.028 22.429 41.52 24.293 40.232 25.564 C 38.264 27.533 35.071 27.534 33.102 25.565 C 31.132 23.596 31.132 20.404 33.101 18.434 Z M 9.497 19.277 C 11.682 18.214 14.359 18.955 15.638 21.028 L 17.512 24.062 C 17.754 24.453 17.897 24.684 18.012 24.845 C 18.067 24.92 18.223 25.034 18.392 24.884 C 18.546 24.755 18.742 24.565 19.074 24.242 C 21.173 22.202 24.662 22.526 26.321 24.946 L 27.79 27.087 C 28.84 28.611 29.147 30.528 28.626 32.303 L 28.197 33.763 C 27.691 35.461 26.492 36.868 24.895 37.636 L 17.855 41.057 C 15.74 42.084 13.237 41.893 11.302 40.557 L 4.987 36.175 C 2.742 34.639 1.765 31.817 2.579 29.221 L 4.229 24.002 C 4.757 22.356 5.939 20.999 7.496 20.249 L 9.498 19.277 Z" fill="rgb(255, 255, 255)"></path><path d="M 28.783 2.801 C 29.116 3.125 29.303 3.569 29.303 4.033 C 29.303 4.497 29.116 4.942 28.783 5.265 L 27.011 7.007 C 26.313 7.687 25.201 7.687 24.504 7.007 C 24.172 6.683 23.985 6.239 23.985 5.776 C 23.985 5.312 24.172 4.868 24.504 4.545 L 26.277 2.803 C 26.974 2.123 28.086 2.123 28.783 2.803 Z M 41.189 2.803 C 41.522 3.127 41.709 3.571 41.709 4.035 C 41.709 4.499 41.522 4.943 41.189 5.267 L 27.01 19.199 C 26.313 19.878 25.201 19.878 24.504 19.199 C 24.172 18.875 23.984 18.431 23.984 17.967 C 23.984 17.503 24.172 17.058 24.504 16.735 L 38.683 2.805 C 39.38 2.125 40.492 2.125 41.189 2.805 Z M 23.467 8.026 C 23.799 8.35 23.986 8.794 23.986 9.257 C 23.986 9.721 23.799 10.165 23.467 10.489 L 18.15 15.714 C 17.453 16.393 16.341 16.393 15.644 15.714 C 15.312 15.39 15.125 14.946 15.125 14.482 C 15.125 14.019 15.312 13.575 15.644 13.251 L 20.961 8.026 C 21.658 7.347 22.77 7.347 23.467 8.026 Z" fill="rgb(255, 255, 255)"></path></svg>',
                        svgContentId: 9544012357,
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-bSX6l.framer-pv9kqr, .framer-bSX6l .framer-pv9kqr { display: block; }",
  ".framer-bSX6l.framer-57w426 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 81px; justify-content: flex-start; overflow: visible; padding: 0px 0px 8px 0px; position: relative; width: 1px; }",
  ".framer-bSX6l .framer-kdvm8l { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: flex-start; overflow: hidden; padding: 0px 0px 0px 1px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-bSX6l .framer-1bivklo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 140px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-bSX6l .framer-1i0me3a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-bSX6l .framer-1h39rvi { flex: none; height: 56px; position: relative; width: 56px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bSX6l.framer-57w426, .framer-bSX6l .framer-kdvm8l, .framer-bSX6l .framer-1bivklo, .framer-bSX6l .framer-1i0me3a { gap: 0px; } .framer-bSX6l.framer-57w426 > *, .framer-bSX6l .framer-kdvm8l > *, .framer-bSX6l .framer-1bivklo > *, .framer-bSX6l .framer-1i0me3a > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-bSX6l.framer-57w426 > :first-child, .framer-bSX6l .framer-kdvm8l > :first-child, .framer-bSX6l .framer-1bivklo > :first-child, .framer-bSX6l .framer-1i0me3a > :first-child { margin-left: 0px; } .framer-bSX6l.framer-57w426 > :last-child, .framer-bSX6l .framer-kdvm8l > :last-child, .framer-bSX6l .framer-1bivklo > :last-child, .framer-bSX6l .framer-1i0me3a > :last-child { margin-right: 0px; } }",
  ".framer-bSX6l.framer-v-1x3hveh.framer-57w426 { width: min-content; }",
  ".framer-bSX6l.framer-v-1x3hveh .framer-kdvm8l { flex: none; width: 140px; }",
  ".framer-bSX6l.framer-v-1x3hveh .framer-1bivklo { align-content: center; align-items: center; justify-content: center; }",
  ".framer-bSX6l.framer-v-5w90xr.framer-57w426 { height: 64px; padding: 0px 0px 7px 0px; }",
  ".framer-bSX6l.framer-v-5w90xr .framer-1bivklo, .framer-bSX6l.framer-v-13se6hj .framer-1bivklo { height: 54px; }",
  ".framer-bSX6l.framer-v-1k0ntq.framer-57w426 { height: 64px; padding: 0px 0px 7px 0px; width: min-content; }",
  ".framer-bSX6l.framer-v-1k0ntq .framer-kdvm8l { flex: none; width: 98px; }",
  ".framer-bSX6l.framer-v-1k0ntq .framer-1bivklo { align-content: center; align-items: center; justify-content: center; width: 98px; }",
  ".framer-bSX6l.framer-v-1k0ntq .framer-1h39rvi { height: 44px; width: 44px; }",
  ".framer-bSX6l.framer-v-13se6hj.framer-57w426 { height: 54px; padding: 0px 0px 5px 0px; }",
  ".framer-bSX6l.framer-v-1dmnua9.framer-57w426 { height: 54px; padding: 0px 0px 5px 0px; width: min-content; }",
  ".framer-bSX6l.framer-v-1dmnua9 .framer-kdvm8l { flex: none; width: 80px; }",
  ".framer-bSX6l.framer-v-1dmnua9 .framer-1bivklo { align-content: center; align-items: center; justify-content: center; width: 80px; }",
  ".framer-bSX6l.framer-v-1dmnua9 .framer-1h39rvi { height: 34px; width: 34px; }",
  ".framer-bSX6l.framer-v-18w6533.framer-57w426 { height: 34px; padding: 0px 0px 4px 0px; }",
  ".framer-bSX6l.framer-v-18w6533 .framer-1bivklo { height: 34px; }",
  ".framer-bSX6l.framer-v-1p5cfew.framer-57w426 { height: 34px; padding: 0px 0px 4px 0px; width: min-content; }",
  ".framer-bSX6l.framer-v-1p5cfew .framer-kdvm8l { flex: none; width: 56px; }",
  ".framer-bSX6l.framer-v-1p5cfew .framer-1bivklo { align-content: center; align-items: center; justify-content: center; width: 56px; }",
  ".framer-bSX6l.framer-v-1p5cfew .framer-1h39rvi { height: 22px; width: 22px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 81
 * @framerIntrinsicWidth 1
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"NFj1vp7St":{"layout":["auto","fixed"]},"X5XFaT1T0":{"layout":["fixed","fixed"]},"v_V6Q3Udx":{"layout":["auto","fixed"]},"ekaJDNXT2":{"layout":["fixed","fixed"]},"e2HhRmGaA":{"layout":["auto","fixed"]},"Gguwbuzjf":{"layout":["fixed","fixed"]},"JYHBin7ud":{"layout":["auto","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerBctQR_Wyd = withCSS(Component, css, "framer-bSX6l");
export default FramerBctQR_Wyd;
FramerBctQR_Wyd.displayName = "Home/PrimaryTitleArrow";
FramerBctQR_Wyd.defaultProps = { height: 81, width: 1 };
addPropertyControls(FramerBctQR_Wyd, {
  variant: {
    options: [
      "h8a_pZJCm",
      "NFj1vp7St",
      "X5XFaT1T0",
      "v_V6Q3Udx",
      "ekaJDNXT2",
      "e2HhRmGaA",
      "Gguwbuzjf",
      "JYHBin7ud",
    ],
    optionTitles: [
      "Monitor_Initial",
      "Monitor_Show",
      "Desktop_Initial",
      "Desktop_Show",
      "Tablet_Initial",
      "Tablet_Show",
      "Phone_Initial",
      "Phone_Show",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerBctQR_Wyd, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerBctQR_Wyd",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerIntrinsicWidth: "1",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"NFj1vp7St":{"layout":["auto","fixed"]},"X5XFaT1T0":{"layout":["fixed","fixed"]},"v_V6Q3Udx":{"layout":["auto","fixed"]},"ekaJDNXT2":{"layout":["fixed","fixed"]},"e2HhRmGaA":{"layout":["auto","fixed"]},"Gguwbuzjf":{"layout":["fixed","fixed"]},"JYHBin7ud":{"layout":["auto","fixed"]}}}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "81",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./BctQR_Wyd.map
