// Generated by Framer (7f988a2)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import SocialInstragram from "https://framerusercontent.com/modules/0eFTUQH8XjGpucsSH75N/j7PMDV40DgALY1jhfLW3/DApmG2lm6.js";
import SocialTwitter from "https://framerusercontent.com/modules/2ItbqtQxUhcQrrEzIGHg/yX33VZR5f5ODv1XwAkf6/QCWB403Ul.js";
import SocialMail from "https://framerusercontent.com/modules/yQSbKzkahgEQJZNOUblx/RJWfo3pzJ16KL0FHLcUK/Uz2YgEWdw.js";
const SocialTwitterFonts = getFonts(SocialTwitter);
const SocialInstragramFonts = getFonts(SocialInstragram);
const SocialMailFonts = getFonts(SocialMail);
const cycleOrder = [
  "OBjAt4_OD",
  "W6y1GIkBT",
  "SB7EB0TcQ",
  "PTEm0r7OH",
  "f3YnFdRPF",
];
const serializationHash = "framer-vmzjN";
const variantClassNames = {
  f3YnFdRPF: "framer-v-fg5t6s",
  OBjAt4_OD: "framer-v-cijr23",
  PTEm0r7OH: "framer-v-etmhf2",
  SB7EB0TcQ: "framer-v-1s23r8w",
  W6y1GIkBT: "framer-v-jz1eyy",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 16,
  delay: 0,
  mass: 1,
  stiffness: 140,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
  Collasped_Dark: "PTEm0r7OH",
  Collasped: "W6y1GIkBT",
  Default: "OBjAt4_OD",
  Expanded_Dark: "f3YnFdRPF",
  Expanded: "SB7EB0TcQ",
};
const getProps = ({ height, id, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    variant:
      (_ref =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref !== void 0
        ? _ref
        : "OBjAt4_OD",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    gestureHandlers,
    gestureVariant,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "OBjAt4_OD",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnter1g7yryr = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    setVariant("SB7EB0TcQ");
  });
  const onMouseLeave1jtyous = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    setVariant("W6y1GIkBT");
  });
  const onMouseEnterud5duc = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    setVariant("f3YnFdRPF");
  });
  const onMouseLeave3p8z5b = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    setVariant("PTEm0r7OH");
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-cijr23",
            className,
            classNames,
          ),
          "data-framer-name": "Default",
          layoutDependency: layoutDependency,
          layoutId: "OBjAt4_OD",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            borderBottomLeftRadius: 50,
            borderBottomRightRadius: 50,
            borderTopLeftRadius: 50,
            borderTopRightRadius: 50,
            ...style,
          },
          ...addPropertyOverrides(
            {
              f3YnFdRPF: {
                "data-framer-name": "Expanded_Dark",
                "data-highlight": true,
                onMouseLeave: onMouseLeave3p8z5b,
              },
              PTEm0r7OH: {
                "data-framer-name": "Collasped_Dark",
                "data-highlight": true,
                onMouseEnter: onMouseEnterud5duc,
              },
              SB7EB0TcQ: {
                "data-framer-name": "Expanded",
                "data-highlight": true,
                onMouseLeave: onMouseLeave1jtyous,
              },
              W6y1GIkBT: {
                "data-framer-name": "Collasped",
                "data-highlight": true,
                onMouseEnter: onMouseEnter1g7yryr,
              },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              width: "54px",
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-49sq04-container",
                layoutDependency: layoutDependency,
                layoutId: "mPkOUb9B0-container",
                children: /*#__PURE__*/ _jsx(SocialTwitter, {
                  height: "100%",
                  id: "mPkOUb9B0",
                  layoutId: "mPkOUb9B0",
                  style: { height: "100%", width: "100%" },
                  variant: "llDAhtHF4",
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      f3YnFdRPF: { variant: "gRpNrhHu5" },
                      PTEm0r7OH: { variant: "gRpNrhHu5" },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              width: "54px",
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-9eyzup-container",
                layoutDependency: layoutDependency,
                layoutId: "GOUcnVjsM-container",
                children: /*#__PURE__*/ _jsx(SocialInstragram, {
                  height: "100%",
                  id: "GOUcnVjsM",
                  layoutId: "GOUcnVjsM",
                  style: { height: "100%", width: "100%" },
                  variant: "YRapQNpGe",
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      f3YnFdRPF: { variant: "qf42jsMmk" },
                      PTEm0r7OH: { variant: "qf42jsMmk" },
                      W6y1GIkBT: { variant: "qrHxSd5Yo" },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              width: "54px",
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-7h5zk3-container",
                layoutDependency: layoutDependency,
                layoutId: "oBgg6yqbF-container",
                children: /*#__PURE__*/ _jsx(SocialMail, {
                  height: "100%",
                  id: "oBgg6yqbF",
                  layoutId: "oBgg6yqbF",
                  style: { height: "100%", width: "100%" },
                  variant: "QkHTEsfZ8",
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      f3YnFdRPF: { variant: "VgQrGJ3F8" },
                      PTEm0r7OH: { variant: "VgQrGJ3F8" },
                      W6y1GIkBT: { variant: "hMKOOSP6K" },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-vmzjN.framer-zl7lx9, .framer-vmzjN .framer-zl7lx9 { display: block; }",
  ".framer-vmzjN.framer-cijr23 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: 54px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: auto; }",
  ".framer-vmzjN .framer-49sq04-container { flex: none; height: 54px; position: relative; width: 54px; z-index: 2; }",
  ".framer-vmzjN .framer-9eyzup-container { flex: none; height: 54px; position: relative; width: 54px; z-index: 1; }",
  ".framer-vmzjN .framer-7h5zk3-container { flex: none; height: 54px; position: relative; width: 54px; z-index: 0; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vmzjN.framer-cijr23 { gap: 0px; } .framer-vmzjN.framer-cijr23 > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-vmzjN.framer-cijr23 > :first-child { margin-left: 0px; } .framer-vmzjN.framer-cijr23 > :last-child { margin-right: 0px; } }",
  ".framer-vmzjN.framer-v-jz1eyy.framer-cijr23, .framer-vmzjN.framer-v-etmhf2.framer-cijr23 { display: block; padding: unset; width: 202px; }",
  ".framer-vmzjN.framer-v-jz1eyy .framer-49sq04-container, .framer-vmzjN.framer-v-etmhf2 .framer-49sq04-container { bottom: 0px; height: unset; left: 0px; position: absolute; top: 0px; z-index: 3; }",
  ".framer-vmzjN.framer-v-jz1eyy .framer-9eyzup-container, .framer-vmzjN.framer-v-etmhf2 .framer-9eyzup-container { bottom: 0px; height: unset; left: 30px; position: absolute; top: 0px; }",
  ".framer-vmzjN.framer-v-jz1eyy .framer-7h5zk3-container, .framer-vmzjN.framer-v-etmhf2 .framer-7h5zk3-container { bottom: 0px; height: unset; left: 60px; position: absolute; top: 0px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vmzjN.framer-v-jz1eyy.framer-cijr23 { gap: 0px; } .framer-vmzjN.framer-v-jz1eyy.framer-cijr23 > *, .framer-vmzjN.framer-v-jz1eyy.framer-cijr23 > :first-child, .framer-vmzjN.framer-v-jz1eyy.framer-cijr23 > :last-child { margin: 0px; } }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vmzjN.framer-v-etmhf2.framer-cijr23 { gap: 0px; } .framer-vmzjN.framer-v-etmhf2.framer-cijr23 > *, .framer-vmzjN.framer-v-etmhf2.framer-cijr23 > :first-child, .framer-vmzjN.framer-v-etmhf2.framer-cijr23 > :last-child { margin: 0px; } }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 54
 * @framerIntrinsicWidth 194
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"W6y1GIkBT":{"layout":["fixed","fixed"]},"SB7EB0TcQ":{"layout":["auto","fixed"]},"PTEm0r7OH":{"layout":["fixed","fixed"]},"f3YnFdRPF":{"layout":["auto","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const Framerew_6tk68D = withCSS(Component, css, "framer-vmzjN");
export default Framerew_6tk68D;
Framerew_6tk68D.displayName = "Social/AdaptiveBar";
Framerew_6tk68D.defaultProps = { height: 54, width: 194 };
addPropertyControls(Framerew_6tk68D, {
  variant: {
    options: ["OBjAt4_OD", "W6y1GIkBT", "SB7EB0TcQ", "PTEm0r7OH", "f3YnFdRPF"],
    optionTitles: [
      "Default",
      "Collasped",
      "Expanded",
      "Collasped_Dark",
      "Expanded_Dark",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  Framerew_6tk68D,
  [
    { explicitInter: true, fonts: [] },
    ...SocialTwitterFonts,
    ...SocialInstragramFonts,
    ...SocialMailFonts,
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerew_6tk68D",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"W6y1GIkBT":{"layout":["fixed","fixed"]},"SB7EB0TcQ":{"layout":["auto","fixed"]},"PTEm0r7OH":{"layout":["fixed","fixed"]},"f3YnFdRPF":{"layout":["auto","fixed"]}}}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerIntrinsicWidth: "194",
        framerIntrinsicHeight: "54",
        framerImmutableVariables: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
