// Generated by Framer (9a49031)
import { jsx as r, jsxs as e } from "react/jsx-runtime";
import {
  addFonts as a,
  addPropertyControls as t,
  ControlType as o,
  cx as i,
  SVG as s,
  useActiveVariantCallback as n,
  useLocaleInfo as d,
  useOnVariantChange as m,
  useVariantState as l,
  withCSS as f,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import {
  LayoutGroup as u,
  motion as p,
  MotionConfigContext as c,
} from "framer-motion";
import * as h from "react";
import * as v from "./FGuSuaCxq-0.js";
let y = ["brTi_c7ZO", "sgVvxIUuI", "oJIUazuxs"],
  g = "framer-mIywZ",
  w = {
    brTi_c7ZO: "framer-v-12g5mhk",
    oJIUazuxs: "framer-v-cmtkfp",
    sgVvxIUuI: "framer-v-swcs80",
  };
function x(r, ...e) {
  let a = {};
  return null == e || e.forEach((e) => e && Object.assign(a, r[e])), a;
}
let b = {
    default: {
      delay: 0,
      duration: 0.2,
      ease: [0.44, 0, 0.56, 1],
      type: "tween",
    },
    oJIUazuxs: {
      delay: 0,
      duration: 0,
      ease: [0.44, 0, 0.56, 1],
      type: "tween",
    },
    sgVvxIUuI: {
      delay: 0,
      duration: 1,
      ease: [0.44, 0, 0.56, 1],
      type: "tween",
    },
  },
  I = { YzTqEHveH: v },
  k = (r, e) => {
    for (; e; ) {
      let a = I[e.id];
      if (a) {
        let e = a[r];
        if (e) return e;
      }
      e = e.fallback;
    }
  },
  U = (r, e) => `translateY(-50%) ${e}`,
  Z = ({ value: e, children: a }) => {
    let t = h.useContext(c),
      o = null != e ? e : t.transition,
      i = h.useMemo(() => ({ ...t, transition: o }), [JSON.stringify(o)]);
    return /*#__PURE__*/ r(c.Provider, { value: i, children: a });
  },
  T = { "Variant 3": "oJIUazuxs", Down: "sgVvxIUuI", Up: "brTi_c7ZO" },
  C = ({ height: r, id: e, width: a, ...t }) => {
    var o, i;
    return {
      ...t,
      variant:
        null !==
          (i = null !== (o = T[t.variant]) && void 0 !== o ? o : t.variant) &&
        void 0 !== i
          ? i
          : "brTi_c7ZO",
    };
  },
  R = (r, e) => e.join("-") + r.layoutDependency,
  V = /*#__PURE__*/ h.forwardRef(function (a, t) {
    let { activeLocale: o } = d(),
      { style: f, className: c, layoutId: v, variant: g, ...I } = C(a),
      {
        baseVariant: k,
        classNames: T,
        gestureVariant: V,
        setGestureState: z,
        setVariant: j,
        transition: q,
        variants: J,
      } = l({
        cycleOrder: y,
        defaultVariant: "brTi_c7ZO",
        transitions: b,
        variant: g,
        variantClassNames: w,
      }),
      O = R(a, J),
      { activeVariantCallback: D, delay: L } = n(k),
      _ = D(async (...r) => {
        await L(() => j("sgVvxIUuI"), 300);
      }),
      H = D(async (...r) => {
        await L(() => j("oJIUazuxs"), 1200);
      }),
      N = D(async (...r) => {
        await L(() => j("brTi_c7ZO"), 100);
      });
    m(k, { default: _, oJIUazuxs: N, sgVvxIUuI: H });
    let P = h.useRef(null),
      B = h.useId();
    return /*#__PURE__*/ r(u, {
      id: null != v ? v : B,
      children: /*#__PURE__*/ r(p.div, {
        initial: g,
        animate: J,
        onHoverStart: () => z({ isHovered: !0 }),
        onHoverEnd: () => z({ isHovered: !1 }),
        onTapStart: () => z({ isPressed: !0 }),
        onTap: () => z({ isPressed: !1 }),
        onTapCancel: () => z({ isPressed: !1 }),
        className: i("framer-mIywZ", ...[], T),
        style: { display: "contents" },
        children: /*#__PURE__*/ r(Z, {
          value: q,
          children: /*#__PURE__*/ e(p.div, {
            ...I,
            className: i("framer-12g5mhk", c),
            "data-framer-name": "Up",
            "data-highlight": !0,
            layoutDependency: O,
            layoutId: "brTi_c7ZO",
            ref: null != t ? t : P,
            style: { ...f },
            ...x(
              {
                oJIUazuxs: { "data-framer-name": "Variant 3" },
                sgVvxIUuI: { "data-framer-name": "Down" },
              },
              k,
              V,
            ),
            children: [
              /*#__PURE__*/ r(s, {
                className: "framer-19718mh",
                "data-framer-name": "rectangular",
                layout: "position",
                layoutDependency: O,
                layoutId: "kwL3fzLZi",
                opacity: 1,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 2 12 C 2 9.2 2 7.8 2.545 6.73 C 3.024 5.789 3.789 5.024 4.73 4.545 C 5.8 4 7.2 4 10 4 L 14 4 C 16.8 4 18.2 4 19.27 4.545 C 20.211 5.024 20.976 5.789 21.455 6.73 C 22 7.8 22 9.2 22 12 C 22 14.8 22 16.2 21.455 17.27 C 20.976 18.211 20.211 18.976 19.27 19.455 C 18.2 20 16.8 20 14 20 L 10 20 C 7.2 20 5.8 20 4.73 19.455 C 3.789 18.976 3.024 18.211 2.545 17.27 C 2 16.2 2 14.8 2 12 Z" fill="transparent" stroke-width="1.8" stroke="var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White 100&quot;} */" stroke-linejoin="round" stroke-dasharray=""></path></svg>',
                svgContentId: 1790040714,
                withExternalLayout: !0,
              }),
              /*#__PURE__*/ r(p.div, {
                className: "framer-1qmegsk",
                layoutDependency: O,
                layoutId: "HP6Dygj54",
                style: {
                  backgroundColor:
                    "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                  borderBottomLeftRadius: 2,
                  borderBottomRightRadius: 2,
                  borderTopLeftRadius: 2,
                  borderTopRightRadius: 2,
                  opacity: 1,
                },
                transformTemplate: U,
                variants: {
                  oJIUazuxs: { opacity: 0 },
                  sgVvxIUuI: { opacity: 0 },
                },
              }),
              /*#__PURE__*/ r(p.div, {
                className: "framer-1skqmnj",
                layoutDependency: O,
                layoutId: "X2bM23iR9",
                style: {
                  backgroundColor:
                    "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                  borderBottomLeftRadius: 2,
                  borderBottomRightRadius: 2,
                  borderTopLeftRadius: 2,
                  borderTopRightRadius: 2,
                  opacity: 1,
                },
                variants: {
                  oJIUazuxs: { opacity: 0 },
                  sgVvxIUuI: { opacity: 0 },
                },
              }),
            ],
          }),
        }),
      }),
    });
  }),
  z = [
    '.framer-mIywZ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
    "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
    ".framer-mIywZ .framer-18h9jd1 { display: block; }",
    ".framer-mIywZ .framer-12g5mhk { height: 42px; position: relative; width: 42px; }",
    ".framer-mIywZ .framer-19718mh { flex: none; height: 24px; left: calc(50.00000000000002% - 24px / 2); position: absolute; top: calc(50.00000000000002% - 24px / 2); width: 24px; }",
    ".framer-mIywZ .framer-1qmegsk { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 4px); overflow: hidden; position: absolute; right: 14px; top: 45%; width: 4px; will-change: var(--framer-will-change-override, transform); }",
    ".framer-mIywZ .framer-1skqmnj { aspect-ratio: 1 / 1; bottom: 16px; flex: none; height: var(--framer-aspect-ratio-supported, 4px); overflow: hidden; position: absolute; right: 16px; width: 4px; will-change: var(--framer-will-change-override, transform); }",
    ".framer-mIywZ.framer-v-swcs80 .framer-12g5mhk, .framer-mIywZ.framer-v-cmtkfp .framer-12g5mhk { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 42px); }",
    ".framer-mIywZ.framer-v-swcs80 .framer-1qmegsk { left: 16px; right: unset; }",
    ".framer-mIywZ.framer-v-swcs80 .framer-1skqmnj { left: 14px; right: unset; }",
  ],
  j = f(V, z, "framer-mIywZ");
export default j;
(j.displayName = "Button/TouchPad"),
  (j.defaultProps = { height: 42, width: 42 }),
  t(j, {
    variant: {
      options: ["brTi_c7ZO", "sgVvxIUuI", "oJIUazuxs"],
      optionTitles: ["Up", "Down", "Variant 3"],
      title: "Variant",
      type: o.Enum,
    },
  }),
  a(j, []);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerFGuSuaCxq",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "42",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"sgVvxIUuI":{"layout":["fixed","fixed"]},"oJIUazuxs":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "42",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./FGuSuaCxq.map
