// Generated by Framer (68f6254)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withMappedReactProps,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import Appearence from "https://framerusercontent.com/modules/IkmROXxT6vYQmp2TxMA5/mdpm8d8I8otsEqnAVIgu/Appearence.js";
import Layouts from "https://framerusercontent.com/modules/b91QEOsl4KTXAK5P6bcq/3larzLTOTTnzOxYPY3RX/Layout.js";
import Settings from "https://framerusercontent.com/modules/RTXV2JNoHl3b5uHFKoCo/lT5W3hQmRrdDjTf9IQmD/Settings.js";
import Volume from "https://framerusercontent.com/modules/DImyq4pMgfIsBXnh0kMt/6ZVAmmk2znFTAHlLghNC/Volume.js";
import { Sound_Switch } from "https://framerusercontent.com/modules/4EvAAVEkDgPgwcvf2mNn/jUrY9g0w15S5aqSzMQ4v/Sound.js";
import {
  Toggle_Layout,
  Toggle_Layout_Mobile,
  Toggle_Setting,
  Toggle_Sound,
  Toggle_Theme,
} from "https://framerusercontent.com/modules/yue1wEIuxL5Wxj17VKpu/rvoe6u8OOiWRrmZZxev9/Toggle.js";
import ButtonBrief, * as ButtonBriefInfo from "https://framerusercontent.com/modules/PkxCpauxgGWWVoBLUlBl/ue9HrMpYZMlKyktTuhYp/byEnpadr8.js";
const AppearenceFonts = getFonts(Appearence);
const MotionDivToggle_Theme = Toggle_Theme(motion.div);
const VolumeFonts = getFonts(Volume);
const VolumeSound_Switch = Sound_Switch(Volume);
const MotionDivToggle_Sound = Toggle_Sound(motion.div);
const LayoutsFonts = getFonts(Layouts);
const ButtonBriefFonts = getFonts(ButtonBrief);
const ButtonBriefToggle_Layout_MobileWithMappedReactPropssgw6wm =
  withMappedReactProps(Toggle_Layout_Mobile(ButtonBrief), ButtonBriefInfo);
const MotionDivToggle_Layout = Toggle_Layout(motion.div);
const SettingsFonts = getFonts(Settings);
const MotionDivToggle_Setting = Toggle_Setting(motion.div);
const cycleOrder = [
  "XwPo9qGC4",
  "BUN0wW2zJ",
  "SvszP6DBu",
  "mDVTviNgh",
  "VO4pi5TV3",
  "PVKpWD7At",
  "fffltztQF",
];
const serializationHash = "framer-fk8oP";
const variantClassNames = {
  BUN0wW2zJ: "framer-v-1p49jud",
  fffltztQF: "framer-v-1h5hpkm",
  mDVTviNgh: "framer-v-11ugt3d",
  PVKpWD7At: "framer-v-1pndmyc",
  SvszP6DBu: "framer-v-115u3sg",
  VO4pi5TV3: "framer-v-12v1w62",
  XwPo9qGC4: "framer-v-9ka035",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 28,
  delay: 0,
  mass: 1,
  stiffness: 178,
  type: "spring",
};
const negate = (value) => {
  return !value;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
  AlwaysDark: "PVKpWD7At",
  AlwaysLight: "fffltztQF",
  Collasped: "BUN0wW2zJ",
  Dark: "mDVTviNgh",
  Default: "XwPo9qGC4",
  Light: "VO4pi5TV3",
  Mobile: "SvszP6DBu",
};
const getProps = ({
  height,
  id,
  layoutCursor,
  layoutVisible,
  mobile,
  setting,
  setting2,
  settingCursor,
  soundCursor,
  soundVisible,
  themeCursor,
  themeVisible,
  width,
  ...props
}) => {
  var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2, _ref3;
  return {
    ...props,
    bW5yPdm2I:
      setting !== null && setting !== void 0 ? setting : props.bW5yPdm2I,
    bzjewZMVz:
      soundCursor !== null && soundCursor !== void 0
        ? soundCursor
        : props.bzjewZMVz,
    D_n_dMzCO: mobile !== null && mobile !== void 0 ? mobile : props.D_n_dMzCO,
    IDjhS4IKl:
      (_ref =
        themeVisible !== null && themeVisible !== void 0
          ? themeVisible
          : props.IDjhS4IKl) !== null && _ref !== void 0
        ? _ref
        : true,
    IgMJMP6ld:
      (_ref1 =
        layoutVisible !== null && layoutVisible !== void 0
          ? layoutVisible
          : props.IgMJMP6ld) !== null && _ref1 !== void 0
        ? _ref1
        : true,
    qRScD7sgw:
      themeCursor !== null && themeCursor !== void 0
        ? themeCursor
        : props.qRScD7sgw,
    uh2rKEoGW:
      layoutCursor !== null && layoutCursor !== void 0
        ? layoutCursor
        : props.uh2rKEoGW,
    uLaa8oUgA:
      setting2 !== null && setting2 !== void 0 ? setting2 : props.uLaa8oUgA,
    variant:
      (_ref2 =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref2 !== void 0
        ? _ref2
        : "XwPo9qGC4",
    VscZCNiuc:
      settingCursor !== null && settingCursor !== void 0
        ? settingCursor
        : props.VscZCNiuc,
    Y6c4BQxZw:
      (_ref3 =
        soundVisible !== null && soundVisible !== void 0
          ? soundVisible
          : props.Y6c4BQxZw) !== null && _ref3 !== void 0
        ? _ref3
        : true,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    bW5yPdm2I,
    D_n_dMzCO,
    uLaa8oUgA,
    qRScD7sgw,
    bzjewZMVz,
    uh2rKEoGW,
    VscZCNiuc,
    IDjhS4IKl,
    Y6c4BQxZw,
    IgMJMP6ld,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "XwPo9qGC4",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap10e5784 = activeVariantCallback(async (...args) => {
    if (bW5yPdm2I) {
      const res = await bW5yPdm2I(...args);
      if (res === false) return false;
    }
    if (uLaa8oUgA) {
      const res = await uLaa8oUgA(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const isDisplayed = (value) => {
    if (baseVariant === "SvszP6DBu") return false;
    if (
      ["mDVTviNgh", "VO4pi5TV3", "PVKpWD7At", "fffltztQF"].includes(baseVariant)
    )
      return true;
    return value;
  };
  const visible = negate(D_n_dMzCO);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-9ka035",
            className,
            classNames,
          ),
          "data-framer-name": "Default",
          layoutDependency: layoutDependency,
          layoutId: "XwPo9qGC4",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style },
          ...addPropertyOverrides(
            {
              BUN0wW2zJ: { "data-framer-name": "Collasped" },
              fffltztQF: { "data-framer-name": "AlwaysLight" },
              mDVTviNgh: { "data-framer-name": "Dark" },
              PVKpWD7At: { "data-framer-name": "AlwaysDark" },
              SvszP6DBu: { "data-framer-name": "Mobile" },
              VO4pi5TV3: { "data-framer-name": "Light" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-dqit7d",
            layoutDependency: layoutDependency,
            layoutId: "SlWd41rtv",
            children: [
              isDisplayed(IDjhS4IKl) &&
                /*#__PURE__*/ _jsx(MotionDivToggle_Theme, {
                  className: "framer-262im6",
                  "data-framer-name": "Theme",
                  layoutDependency: layoutDependency,
                  layoutId: "N0zbtGBIn",
                  style: { opacity: 1 },
                  variants: { BUN0wW2zJ: { opacity: 0 } },
                  children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1o068vx-container",
                      "data-framer-cursor": qRScD7sgw,
                      layoutDependency: layoutDependency,
                      layoutId: "tVTbfPycP-container",
                      children: /*#__PURE__*/ _jsx(Appearence, {
                        color:
                          "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                        fill_tap:
                          "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                        fill: "var(--token-b7850564-586d-46b0-98d2-820c4ec87b3f, rgba(255, 255, 255, 0))",
                        height: "100%",
                        hover_color:
                          "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                        hover_effect: true,
                        id: "tVTbfPycP",
                        layoutId: "tVTbfPycP",
                        width: "100%",
                        ...addPropertyOverrides(
                          {
                            fffltztQF: { color: "rgb(255, 255, 255)" },
                            PVKpWD7At: { color: "rgb(0, 0, 0)" },
                            VO4pi5TV3: {
                              color:
                                "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    }),
                  }),
                }),
              isDisplayed(Y6c4BQxZw) &&
                /*#__PURE__*/ _jsx(MotionDivToggle_Sound, {
                  className: "framer-pc5gro",
                  "data-framer-name": "Sound",
                  layoutDependency: layoutDependency,
                  layoutId: "GbwuyHnbC",
                  style: { opacity: 1 },
                  variants: { BUN0wW2zJ: { opacity: 0 } },
                  children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1f44v0i-container",
                      "data-framer-cursor": bzjewZMVz,
                      layoutDependency: layoutDependency,
                      layoutId: "tfhlwtX48-container",
                      children: /*#__PURE__*/ _jsx(VolumeSound_Switch, {
                        color:
                          "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                        fill_tap:
                          "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                        fill: "var(--token-b7850564-586d-46b0-98d2-820c4ec87b3f, rgba(255, 255, 255, 0))",
                        height: "100%",
                        hover_color:
                          "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                        hover_effect: true,
                        id: "tfhlwtX48",
                        layoutId: "tfhlwtX48",
                        width: "100%",
                        ...addPropertyOverrides(
                          {
                            fffltztQF: { color: "rgb(255, 255, 255)" },
                            PVKpWD7At: { color: "rgb(0, 0, 0)" },
                            VO4pi5TV3: {
                              color:
                                "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    }),
                  }),
                }),
              isDisplayed(IgMJMP6ld) &&
                /*#__PURE__*/ _jsxs(MotionDivToggle_Layout, {
                  className: "framer-sl3rr1",
                  "data-framer-name": "Layout",
                  layoutDependency: layoutDependency,
                  layoutId: "N17OAQqYk",
                  style: { opacity: 1 },
                  variants: { BUN0wW2zJ: { opacity: 0 } },
                  children: [
                    visible &&
                      /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(motion.div, {
                          className: "framer-e5f2ip-container",
                          "data-framer-cursor": uh2rKEoGW,
                          layoutDependency: layoutDependency,
                          layoutId: "begQRLCEU-container",
                          children: /*#__PURE__*/ _jsx(Layouts, {
                            color:
                              "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                            fill_tap:
                              "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                            fill: "var(--token-b7850564-586d-46b0-98d2-820c4ec87b3f, rgba(255, 255, 255, 0))",
                            height: "100%",
                            hover_color:
                              "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                            id: "begQRLCEU",
                            layoutId: "begQRLCEU",
                            width: "100%",
                            ...addPropertyOverrides(
                              {
                                fffltztQF: { color: "rgb(255, 255, 255)" },
                                PVKpWD7At: { color: "rgb(0, 0, 0)" },
                                VO4pi5TV3: {
                                  color:
                                    "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                        }),
                      }),
                    D_n_dMzCO &&
                      /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(motion.div, {
                          className: "framer-10wvtsj-container",
                          layoutDependency: layoutDependency,
                          layoutId: "h94qIsUTG-container",
                          children: /*#__PURE__*/ _jsx(
                            ButtonBriefToggle_Layout_MobileWithMappedReactPropssgw6wm,
                            {
                              height: "100%",
                              id: "h94qIsUTG",
                              layoutId: "h94qIsUTG",
                              style: { height: "100%", width: "100%" },
                              variant: "F3z2GrFiS",
                              width: "100%",
                            },
                          ),
                        }),
                      }),
                  ],
                }),
              /*#__PURE__*/ _jsx(MotionDivToggle_Setting, {
                className: "framer-16ymgku",
                "data-framer-name": "Setting",
                "data-highlight": true,
                layoutDependency: layoutDependency,
                layoutId: "nzSq6qPBM",
                onTap: onTap10e5784,
                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  children: /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1mx905s-container",
                    "data-framer-cursor": VscZCNiuc,
                    layoutDependency: layoutDependency,
                    layoutId: "AzYZK8l1Y-container",
                    children: /*#__PURE__*/ _jsx(Settings, {
                      color:
                        "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                      fill_tap:
                        "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                      fill: "var(--token-b7850564-586d-46b0-98d2-820c4ec87b3f, rgba(255, 255, 255, 0))",
                      height: "100%",
                      hover_color:
                        "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                      id: "AzYZK8l1Y",
                      layoutId: "AzYZK8l1Y",
                      width: "100%",
                      ...addPropertyOverrides(
                        {
                          fffltztQF: { color: "rgb(255, 255, 255)" },
                          PVKpWD7At: { color: "rgb(0, 0, 0)" },
                          VO4pi5TV3: {
                            color:
                              "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                          },
                        },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  }),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-fk8oP.framer-kfmh6w, .framer-fk8oP .framer-kfmh6w { display: block; }",
  ".framer-fk8oP.framer-9ka035 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 42px; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-fk8oP .framer-dqit7d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 42px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-fk8oP .framer-262im6, .framer-fk8oP .framer-pc5gro { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-fk8oP .framer-1o068vx-container, .framer-fk8oP .framer-1f44v0i-container, .framer-fk8oP .framer-e5f2ip-container, .framer-fk8oP .framer-1mx905s-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-fk8oP .framer-sl3rr1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-fk8oP .framer-10wvtsj-container { flex: none; height: 42px; position: relative; width: 42px; }",
  ".framer-fk8oP .framer-16ymgku { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-fk8oP.framer-9ka035, .framer-fk8oP .framer-dqit7d, .framer-fk8oP .framer-262im6, .framer-fk8oP .framer-pc5gro, .framer-fk8oP .framer-sl3rr1, .framer-fk8oP .framer-16ymgku { gap: 0px; } .framer-fk8oP.framer-9ka035 > *, .framer-fk8oP .framer-sl3rr1 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-fk8oP.framer-9ka035 > :first-child, .framer-fk8oP .framer-dqit7d > :first-child, .framer-fk8oP .framer-262im6 > :first-child, .framer-fk8oP .framer-pc5gro > :first-child, .framer-fk8oP .framer-sl3rr1 > :first-child { margin-left: 0px; } .framer-fk8oP.framer-9ka035 > :last-child, .framer-fk8oP .framer-dqit7d > :last-child, .framer-fk8oP .framer-262im6 > :last-child, .framer-fk8oP .framer-pc5gro > :last-child, .framer-fk8oP .framer-sl3rr1 > :last-child { margin-right: 0px; } .framer-fk8oP .framer-dqit7d > *, .framer-fk8oP .framer-262im6 > *, .framer-fk8oP .framer-pc5gro > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-fk8oP .framer-16ymgku > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-fk8oP .framer-16ymgku > :first-child { margin-top: 0px; } .framer-fk8oP .framer-16ymgku > :last-child { margin-bottom: 0px; } }",
  ".framer-fk8oP.framer-v-1p49jud.framer-9ka035 { justify-content: center; }",
  ".framer-fk8oP.framer-v-1p49jud .framer-dqit7d { justify-content: flex-end; width: 94px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 42
 * @framerIntrinsicWidth 198
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"BUN0wW2zJ":{"layout":["auto","fixed"]},"SvszP6DBu":{"layout":["auto","fixed"]},"mDVTviNgh":{"layout":["auto","fixed"]},"VO4pi5TV3":{"layout":["auto","fixed"]},"PVKpWD7At":{"layout":["auto","fixed"]},"fffltztQF":{"layout":["auto","fixed"]}}}
 * @framerVariables {"bW5yPdm2I":"setting","D_n_dMzCO":"mobile","uLaa8oUgA":"setting2","qRScD7sgw":"themeCursor","bzjewZMVz":"soundCursor","uh2rKEoGW":"layoutCursor","VscZCNiuc":"settingCursor","IDjhS4IKl":"themeVisible","Y6c4BQxZw":"soundVisible","IgMJMP6ld":"layoutVisible"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerhII_2ClpN = withCSS(Component, css, "framer-fk8oP");
export default FramerhII_2ClpN;
FramerhII_2ClpN.displayName = "Home/Status";
FramerhII_2ClpN.defaultProps = { height: 42, width: 198 };
addPropertyControls(FramerhII_2ClpN, {
  variant: {
    options: [
      "XwPo9qGC4",
      "BUN0wW2zJ",
      "SvszP6DBu",
      "mDVTviNgh",
      "VO4pi5TV3",
      "PVKpWD7At",
      "fffltztQF",
    ],
    optionTitles: [
      "Default",
      "Collasped",
      "Mobile",
      "Dark",
      "Light",
      "AlwaysDark",
      "AlwaysLight",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  bW5yPdm2I: { title: "Setting", type: ControlType.EventHandler },
  D_n_dMzCO: {
    defaultValue: false,
    title: "Mobile",
    type: ControlType.Boolean,
  },
  uLaa8oUgA: { title: "Setting 2", type: ControlType.EventHandler },
  qRScD7sgw: { title: "Theme Cursor", type: ControlType.CustomCursor },
  bzjewZMVz: { title: "Sound Cursor", type: ControlType.CustomCursor },
  uh2rKEoGW: { title: "Layout Cursor", type: ControlType.CustomCursor },
  VscZCNiuc: { title: "Setting Cursor", type: ControlType.CustomCursor },
  IDjhS4IKl: {
    defaultValue: true,
    title: "Theme Visible",
    type: ControlType.Boolean,
  },
  Y6c4BQxZw: {
    defaultValue: true,
    title: "Sound Visible",
    type: ControlType.Boolean,
  },
  IgMJMP6ld: {
    defaultValue: true,
    title: "Layout Visible",
    type: ControlType.Boolean,
  },
});
addFonts(
  FramerhII_2ClpN,
  [
    { explicitInter: true, fonts: [] },
    ...AppearenceFonts,
    ...VolumeFonts,
    ...LayoutsFonts,
    ...ButtonBriefFonts,
    ...SettingsFonts,
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerhII_2ClpN",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerVariables:
          '{"bW5yPdm2I":"setting","D_n_dMzCO":"mobile","uLaa8oUgA":"setting2","qRScD7sgw":"themeCursor","bzjewZMVz":"soundCursor","uh2rKEoGW":"layoutCursor","VscZCNiuc":"settingCursor","IDjhS4IKl":"themeVisible","Y6c4BQxZw":"soundVisible","IgMJMP6ld":"layoutVisible"}',
        framerIntrinsicWidth: "198",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "42",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"BUN0wW2zJ":{"layout":["auto","fixed"]},"SvszP6DBu":{"layout":["auto","fixed"]},"mDVTviNgh":{"layout":["auto","fixed"]},"VO4pi5TV3":{"layout":["auto","fixed"]},"PVKpWD7At":{"layout":["auto","fixed"]},"fffltztQF":{"layout":["auto","fixed"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
