// Generated by Framer (6b748fa)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Link,
  RichText,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Time as TimeDate } from "https://framerusercontent.com/modules/1rQY6iWLBRAy4KOToV43/2flqgkuiGOdvx08xbuiW/Time.js";
import {
  Language_Chn_Content,
  Language_En_Content,
} from "https://framerusercontent.com/modules/yue1wEIuxL5Wxj17VKpu/rvoe6u8OOiWRrmZZxev9/Toggle.js";
import * as sharedStyle from "https://framerusercontent.com/modules/IJuPkH75DrOaXa8hMB2D/uNPycaMZJ1T8jriUTsGK/sSyE5_N0_.js";
const TimeDateFonts = getFonts(TimeDate);
const RichTextLanguage_Chn_Content = Language_Chn_Content(RichText);
const RichTextLanguage_En_Content = Language_En_Content(RichText);
const cycleOrder = [
  "sMkGer26K",
  "HA6UEnA7B",
  "QNjUH3XFk",
  "jFBqLEFyq",
  "GNYLhonpo",
  "kgj0tpTsU",
  "UsOW_dk_D",
  "w625aUNa9",
];
const serializationHash = "framer-FcFnE";
const variantClassNames = {
  GNYLhonpo: "framer-v-1lom2uu",
  HA6UEnA7B: "framer-v-18bi0ba",
  jFBqLEFyq: "framer-v-1bjz902",
  kgj0tpTsU: "framer-v-1wq57wq",
  QNjUH3XFk: "framer-v-kxyvev",
  sMkGer26K: "framer-v-1brt7yu",
  UsOW_dk_D: "framer-v-1bnasks",
  w625aUNa9: "framer-v-b8ewg7",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
  "Variant 7": "UsOW_dk_D",
  Framer_Dark: "kgj0tpTsU",
  Framer_Light: "jFBqLEFyq",
  Framer: "HA6UEnA7B",
  FramerOnly: "w625aUNa9",
  Time_Dark: "GNYLhonpo",
  Time_Light: "QNjUH3XFk",
  Time: "sMkGer26K",
};
const getProps = ({ height, id, title, width, ...props }) => {
  var _ref, _humanReadableVariantMap_props_variant, _ref1;
  return {
    ...props,
    OZYV48tII:
      (_ref = title !== null && title !== void 0 ? title : props.OZYV48tII) !==
        null && _ref !== void 0
        ? _ref
        : "GMT+8",
    variant:
      (_ref1 =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref1 !== void 0
        ? _ref1
        : "sMkGer26K",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, OZYV48tII, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "sMkGer26K",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseLeave14u0jot = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    setVariant("sMkGer26K");
  });
  const onMouseEnter5zcoqn = activeVariantCallback(async (...args) => {
    setVariant("HA6UEnA7B");
  });
  const onMouseEnter1j3uwu4 = activeVariantCallback(async (...args) => {
    setVariant("jFBqLEFyq");
  });
  const onMouseEnterxst180 = activeVariantCallback(async (...args) => {
    setVariant("kgj0tpTsU");
  });
  const onMouseLeaveigq8p2 = activeVariantCallback(async (...args) => {
    setVariant("QNjUH3XFk");
  });
  const onMouseLeave9byy6z = activeVariantCallback(async (...args) => {
    setVariant("GNYLhonpo");
  });
  const ref1 = React.useRef(null);
  const isDisplayed = () => {
    if (baseVariant === "w625aUNa9") return false;
    return true;
  };
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [sharedStyle.className];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: "https://www.framer.com?via=jayzhushi",
          ...addPropertyOverrides(
            { HA6UEnA7B: { openInNewTab: true } },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(serializationHash, ...sharedStyleClassNames, "framer-1brt7yu", className, classNames)} framer-mk1gl5`,
            "data-framer-name": "Time",
            layoutDependency: layoutDependency,
            layoutId: "sMkGer26K",
            ref: ref !== null && ref !== void 0 ? ref : ref1,
            style: {
              borderBottomLeftRadius: 40,
              borderBottomRightRadius: 40,
              borderTopLeftRadius: 40,
              borderTopRightRadius: 40,
              ...style,
            },
            ...addPropertyOverrides(
              {
                GNYLhonpo: { "data-framer-name": "Time_Dark" },
                HA6UEnA7B: {
                  "data-framer-name": "Framer",
                  "data-highlight": true,
                  onMouseLeave: onMouseLeave14u0jot,
                },
                jFBqLEFyq: { "data-framer-name": "Framer_Light" },
                kgj0tpTsU: { "data-framer-name": "Framer_Dark" },
                QNjUH3XFk: { "data-framer-name": "Time_Light" },
                UsOW_dk_D: { "data-framer-name": "Variant 7" },
                w625aUNa9: { "data-framer-name": "FramerOnly" },
              },
              baseVariant,
              gestureVariant,
            ),
            children: [
              isDisplayed() &&
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-drxj91",
                  "data-highlight": true,
                  layoutDependency: layoutDependency,
                  layoutId: "ZGXPp9km3",
                  onMouseEnter: onMouseEnter5zcoqn,
                  ...addPropertyOverrides(
                    {
                      GNYLhonpo: { onMouseEnter: onMouseEnterxst180 },
                      jFBqLEFyq: { onMouseEnter: onMouseEnter1j3uwu4 },
                      kgj0tpTsU: { onMouseEnter: onMouseEnterxst180 },
                      QNjUH3XFk: { onMouseEnter: onMouseEnter1j3uwu4 },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                  children: [
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector":
                              "RlM7Q2FiaW5ldCBHcm90ZXNrLW1lZGl1bQ==",
                            "--framer-font-family":
                              '"Cabinet Grotesk", sans-serif',
                            "--framer-font-size": "19px",
                            "--framer-font-weight": "500",
                            "--framer-line-height": "1em",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-cb5833a4-e810-427d-93f0-14fa8b4ce0f8, rgba(0, 0, 0, 0.5)))",
                          },
                          children: "GMT+8",
                        }),
                      }),
                      className: "framer-1mp5c36",
                      fonts: ["FS;Cabinet Grotesk-medium"],
                      layoutDependency: layoutDependency,
                      layoutId: "spvG5gaJO",
                      style: {
                        "--extracted-r6o4lv":
                          "var(--token-cb5833a4-e810-427d-93f0-14fa8b4ce0f8, rgba(0, 0, 0, 0.5))",
                        "--framer-link-text-color": "rgb(0, 153, 255)",
                        "--framer-link-text-decoration": "underline",
                      },
                      text: OZYV48tII,
                      variants: {
                        GNYLhonpo: {
                          "--extracted-r6o4lv": "rgba(0, 0, 0, 0.5)",
                        },
                        jFBqLEFyq: {
                          "--extracted-r6o4lv": "rgba(255, 255, 255, 0.5)",
                        },
                        kgj0tpTsU: {
                          "--extracted-r6o4lv": "rgba(0, 0, 0, 0.5)",
                        },
                        QNjUH3XFk: {
                          "--extracted-r6o4lv": "rgba(255, 255, 255, 0.5)",
                        },
                      },
                      verticalAlignment: "top",
                      withExternalLayout: true,
                      ...addPropertyOverrides(
                        {
                          GNYLhonpo: {
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "RlM7Q2FiaW5ldCBHcm90ZXNrLW1lZGl1bQ==",
                                  "--framer-font-family":
                                    '"Cabinet Grotesk", sans-serif',
                                  "--framer-font-size": "19px",
                                  "--framer-font-weight": "500",
                                  "--framer-line-height": "1em",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgba(0, 0, 0, 0.5))",
                                },
                                children: "GMT+8",
                              }),
                            }),
                          },
                          jFBqLEFyq: {
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "RlM7Q2FiaW5ldCBHcm90ZXNrLW1lZGl1bQ==",
                                  "--framer-font-family":
                                    '"Cabinet Grotesk", "Cabinet Grotesk Placeholder", sans-serif',
                                  "--framer-font-size": "19px",
                                  "--framer-font-weight": "500",
                                  "--framer-line-height": "1em",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.5))",
                                },
                                children: "GMT+8",
                              }),
                            }),
                          },
                          kgj0tpTsU: {
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "RlM7Q2FiaW5ldCBHcm90ZXNrLW1lZGl1bQ==",
                                  "--framer-font-family":
                                    '"Cabinet Grotesk", sans-serif',
                                  "--framer-font-size": "19px",
                                  "--framer-font-weight": "500",
                                  "--framer-line-height": "1em",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgba(0, 0, 0, 0.5))",
                                },
                                children: "GMT+8",
                              }),
                            }),
                          },
                          QNjUH3XFk: {
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "RlM7Q2FiaW5ldCBHcm90ZXNrLW1lZGl1bQ==",
                                  "--framer-font-family":
                                    '"Cabinet Grotesk", "Cabinet Grotesk Placeholder", sans-serif',
                                  "--framer-font-size": "19px",
                                  "--framer-font-weight": "500",
                                  "--framer-line-height": "1em",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.5))",
                                },
                                children: "GMT+8",
                              }),
                            }),
                          },
                        },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1x3gcao-container",
                        layoutDependency: layoutDependency,
                        layoutId: "kFh6EsGa_-container",
                        children: /*#__PURE__*/ _jsx(TimeDate, {
                          color:
                            "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                          customLocale: "zh-hk",
                          font: {
                            fontFamily:
                              '"Cabinet Grotesk", "Cabinet Grotesk Placeholder", sans-serif',
                            fontSize: "19px",
                            fontStyle: "normal",
                            fontWeight: 500,
                            letterSpacing: "0em",
                            lineHeight: "1em",
                          },
                          height: "100%",
                          id: "kFh6EsGa_",
                          layoutId: "kFh6EsGa_",
                          localeType: "custom",
                          monthFormat: "long",
                          outputType: "time",
                          showHours: true,
                          showMinutes: true,
                          showSeconds: false,
                          showWeekday: true,
                          showYear: true,
                          style: { height: "100%" },
                          timeFormat: "24h",
                          width: "100%",
                          ...addPropertyOverrides(
                            {
                              GNYLhonpo: { color: "rgb(0, 0, 0)" },
                              jFBqLEFyq: { color: "rgb(255, 255, 255)" },
                              kgj0tpTsU: { color: "rgb(0, 0, 0)" },
                              QNjUH3XFk: { color: "rgb(255, 255, 255)" },
                            },
                            baseVariant,
                            gestureVariant,
                          ),
                        }),
                      }),
                    }),
                  ],
                }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-16oq31z",
                layoutDependency: layoutDependency,
                layoutId: "ugviWVBSt",
                style: {
                  borderBottomLeftRadius: 30,
                  borderBottomRightRadius: 30,
                  borderTopLeftRadius: 30,
                  borderTopRightRadius: 30,
                },
                ...addPropertyOverrides(
                  {
                    GNYLhonpo: {
                      "data-highlight": true,
                      onMouseLeave: onMouseLeave9byy6z,
                    },
                    jFBqLEFyq: {
                      "data-highlight": true,
                      onMouseLeave: onMouseLeaveigq8p2,
                    },
                    kgj0tpTsU: {
                      "data-highlight": true,
                      onMouseLeave: onMouseLeave9byy6z,
                    },
                    QNjUH3XFk: {
                      "data-highlight": true,
                      onMouseLeave: onMouseLeaveigq8p2,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
                children: [
                  /*#__PURE__*/ _jsx(SVG, {
                    className: "framer-utttmh",
                    "data-framer-name": "framer",
                    layout: "position",
                    layoutDependency: layoutDependency,
                    layoutId: "pwb5kmxFw",
                    opacity: 1,
                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 10 7 L 16 13 L 4 13 L 4 7 L 10 7 L 4 1 L 16 1 L 16 7 Z M 10 19 L 4 13 L 10 13 Z" fill="var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0)) /* {&quot;name&quot;:&quot;Black 100&quot;} */"></path></svg>',
                    svgContentId: 9009529556,
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        GNYLhonpo: {
                          svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 10 7 L 16 13 L 4 13 L 4 7 L 10 7 L 4 1 L 16 1 L 16 7 Z M 10 19 L 4 13 L 10 13 Z" fill="rgb(0, 0, 0)"></path></svg>',
                          svgContentId: 9162718972,
                        },
                        jFBqLEFyq: {
                          svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 10 7 L 16 13 L 4 13 L 4 7 L 10 7 L 4 1 L 16 1 L 16 7 Z M 10 19 L 4 13 L 10 13 Z" fill="rgb(255, 255, 255)"></path></svg>',
                          svgContentId: 9656486514,
                        },
                        kgj0tpTsU: {
                          svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 10 7 L 16 13 L 4 13 L 4 7 L 10 7 L 4 1 L 16 1 L 16 7 Z M 10 19 L 4 13 L 10 13 Z" fill="rgb(0, 0, 0)"></path></svg>',
                          svgContentId: 9162718972,
                        },
                        QNjUH3XFk: {
                          svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 10 7 L 16 13 L 4 13 L 4 7 L 10 7 L 4 1 L 16 1 L 16 7 Z M 10 19 L 4 13 L 10 13 Z" fill="rgb(255, 255, 255)"></path></svg>',
                          svgContentId: 9656486514,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichTextLanguage_Chn_Content, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-9jlebu",
                        "data-styles-preset": "sSyE5_N0_",
                        children: "使用 Framer 创建",
                      }),
                    }),
                    className: "framer-cc8i5u",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "nXvjNl9qR",
                    style: {
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    variants: {
                      GNYLhonpo: { "--extracted-r6o4lv": "rgb(0, 0, 0)" },
                      jFBqLEFyq: { "--extracted-r6o4lv": "rgb(255, 255, 255)" },
                      kgj0tpTsU: { "--extracted-r6o4lv": "rgb(0, 0, 0)" },
                      QNjUH3XFk: { "--extracted-r6o4lv": "rgb(255, 255, 255)" },
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        GNYLhonpo: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-9jlebu",
                              "data-styles-preset": "sSyE5_N0_",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(0, 0, 0))",
                              },
                              children: "使用 Framer 创建",
                            }),
                          }),
                        },
                        jFBqLEFyq: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-9jlebu",
                              "data-styles-preset": "sSyE5_N0_",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                              },
                              children: "使用 Framer 创建",
                            }),
                          }),
                        },
                        kgj0tpTsU: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-9jlebu",
                              "data-styles-preset": "sSyE5_N0_",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(0, 0, 0))",
                              },
                              children: "使用 Framer 创建",
                            }),
                          }),
                        },
                        QNjUH3XFk: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-9jlebu",
                              "data-styles-preset": "sSyE5_N0_",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                              },
                              children: "使用 Framer 创建",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichTextLanguage_En_Content, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-9jlebu",
                        "data-styles-preset": "sSyE5_N0_",
                        children: "Made in Framer",
                      }),
                    }),
                    className: "framer-y1pl5p",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "j5XDl70I2",
                    style: {
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-FcFnE.framer-mk1gl5, .framer-FcFnE .framer-mk1gl5 { display: block; }",
  ".framer-FcFnE.framer-1brt7yu { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 150px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-FcFnE .framer-drxj91 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 150px; }",
  ".framer-FcFnE .framer-1mp5c36 { flex: none; height: 18px; position: relative; white-space: pre; width: auto; }",
  ".framer-FcFnE .framer-1x3gcao-container { flex: none; height: 19px; position: relative; width: auto; }",
  ".framer-FcFnE .framer-16oq31z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 24px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 150px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  ".framer-FcFnE .framer-utttmh { flex: none; height: 20px; position: relative; width: 20px; }",
  ".framer-FcFnE .framer-cc8i5u, .framer-FcFnE .framer-y1pl5p { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FcFnE.framer-1brt7yu, .framer-FcFnE .framer-drxj91, .framer-FcFnE .framer-16oq31z { gap: 0px; } .framer-FcFnE.framer-1brt7yu > *, .framer-FcFnE .framer-drxj91 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-FcFnE.framer-1brt7yu > :first-child, .framer-FcFnE .framer-drxj91 > :first-child, .framer-FcFnE .framer-16oq31z > :first-child { margin-left: 0px; } .framer-FcFnE.framer-1brt7yu > :last-child, .framer-FcFnE .framer-drxj91 > :last-child, .framer-FcFnE .framer-16oq31z > :last-child { margin-right: 0px; } .framer-FcFnE .framer-16oq31z > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } }",
  ".framer-FcFnE.framer-v-18bi0ba.framer-1brt7yu, .framer-FcFnE.framer-v-1bjz902.framer-1brt7yu, .framer-FcFnE.framer-v-1wq57wq.framer-1brt7yu { justify-content: flex-end; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 24
 * @framerIntrinsicWidth 150
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"HA6UEnA7B":{"layout":["fixed","auto"]},"QNjUH3XFk":{"layout":["fixed","auto"]},"jFBqLEFyq":{"layout":["fixed","auto"]},"GNYLhonpo":{"layout":["fixed","auto"]},"kgj0tpTsU":{"layout":["fixed","auto"]},"UsOW_dk_D":{"layout":["fixed","auto"]},"w625aUNa9":{"layout":["fixed","auto"]}}}
 * @framerVariables {"OZYV48tII":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const Frameri2r6quyI_ = withCSS(Component, css, "framer-FcFnE");
export default Frameri2r6quyI_;
Frameri2r6quyI_.displayName = "Footer/Time";
Frameri2r6quyI_.defaultProps = { height: 24, width: 150 };
addPropertyControls(Frameri2r6quyI_, {
  variant: {
    options: [
      "sMkGer26K",
      "HA6UEnA7B",
      "QNjUH3XFk",
      "jFBqLEFyq",
      "GNYLhonpo",
      "kgj0tpTsU",
      "UsOW_dk_D",
      "w625aUNa9",
    ],
    optionTitles: [
      "Time",
      "Framer",
      "Time_Light",
      "Framer_Light",
      "Time_Dark",
      "Framer_Dark",
      "Variant 7",
      "FramerOnly",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  OZYV48tII: {
    defaultValue: "GMT+8",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
});
addFonts(
  Frameri2r6quyI_,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cabinet Grotesk",
          source: "fontshare",
          style: "normal",
          url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CKQBK2QBTCDREE7L3MXZ3PPW7LDNJCWU/OTOY7FQFSFOJVZKJWKO2EHUJLOGBDN4Q/4CO2ETY7NITKLUDKMYJ75RHJSPHOJ7XT.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
          weight: "400",
        },
      ],
    },
    ...TimeDateFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Frameri2r6quyI_",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "150",
        framerIntrinsicHeight: "24",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"HA6UEnA7B":{"layout":["fixed","auto"]},"QNjUH3XFk":{"layout":["fixed","auto"]},"jFBqLEFyq":{"layout":["fixed","auto"]},"GNYLhonpo":{"layout":["fixed","auto"]},"kgj0tpTsU":{"layout":["fixed","auto"]},"UsOW_dk_D":{"layout":["fixed","auto"]},"w625aUNa9":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerVariables: '{"OZYV48tII":"title"}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
