// Generated by Framer (6b748fa)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  Floating,
  getFonts,
  getFontsFromSharedStyle,
  getPropertyControls,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOverlayState,
  useVariantState,
  withCSS,
  withFX,
  withMappedReactProps,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import {
  AnimatePresence,
  LayoutGroup,
  motion,
  MotionConfigContext,
} from "framer-motion";
import * as React from "react";
import Mailchimp from "https://framerusercontent.com/modules/0ZSF8VJcL5AhXebKiUw3/nbsZGufHZBGrLw7CNirb/Mailchimp.js";
import {
  BackTop_Visibility,
  Social_Visibility,
} from "https://framerusercontent.com/modules/RGCgkyyKvYCOcpgTFJih/l8apYUQ1NMMBi28Mu8sO/Page.js";
import { Effect_MagicHover } from "https://framerusercontent.com/modules/yue1wEIuxL5Wxj17VKpu/rvoe6u8OOiWRrmZZxev9/Toggle.js";
import SoundPicker from "https://framerusercontent.com/modules/CvGigTTgCBqyZO02gJUh/CVnKs90WxfWXyC90xdIU/SoundPicker.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/IJuPkH75DrOaXa8hMB2D/uNPycaMZJ1T8jriUTsGK/sSyE5_N0_.js";
import * as sharedStyle from "https://framerusercontent.com/modules/ztTZI54upesJ4jQU3PX2/kY0YE8vX4mTWg00HOYGw/tvtD0bAK1.js";
import ButtonContact, * as ButtonContactInfo from "https://framerusercontent.com/modules/pUGxcUytjlJHowFsJI3Q/pia3lOSag069FUN3jFt9/Dlnn4rFKe.js";
import SocialAdaptiveBar, * as SocialAdaptiveBarInfo from "https://framerusercontent.com/modules/fgoMYG6j3lNzWyWcyMmK/vczB40IJayoeq8XLYxJ9/ew_6tk68D.js";
import HomeFooterCorner, * as HomeFooterCornerInfo from "https://framerusercontent.com/modules/dBhfV27z3vqGegkKAYl1/faebBVQ7FxRSLU6mRoIQ/t38tnYcdR.js";
const SocialAdaptiveBarFonts = getFonts(SocialAdaptiveBar);
const SocialAdaptiveBarSocial_VisibilityWithMappedReactPropst64o6r =
  withMappedReactProps(
    Social_Visibility(SocialAdaptiveBar),
    SocialAdaptiveBarInfo,
  );
const HomeFooterCornerFonts = getFonts(HomeFooterCorner);
const HomeFooterCornerBackTop_VisibilityWithMappedReactPropsrq5dlk =
  withMappedReactProps(
    BackTop_Visibility(HomeFooterCorner),
    HomeFooterCornerInfo,
  );
const ButtonContactFonts = getFonts(ButtonContact);
const ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06 =
  withMappedReactProps(Effect_MagicHover(ButtonContact), ButtonContactInfo);
const MailchimpFonts = getFonts(Mailchimp);
const MotionDivWithFX = withFX(motion.div);
const SoundPickerFonts = getFonts(SoundPicker);
const HomeFooterCornerControls = getPropertyControls(HomeFooterCorner);
const cycleOrder = [
  "v2CwCl_6S",
  "Qjx7lyGdh",
  "pmZTzPtc9",
  "pC552Hdl2",
  "e6RicA5Ai",
  "gNhJe7Fbj",
  "tdBhGfIRW",
  "L0sdqDSt8",
];
const serializationHash = "framer-8RpJg";
const variantClassNames = {
  e6RicA5Ai: "framer-v-vhu433",
  gNhJe7Fbj: "framer-v-wnqb0w",
  L0sdqDSt8: "framer-v-1wc2ac0",
  pC552Hdl2: "framer-v-n56b7x",
  pmZTzPtc9: "framer-v-1bet4wy",
  Qjx7lyGdh: "framer-v-tizt5h",
  tdBhGfIRW: "framer-v-1ql8g3o",
  v2CwCl_6S: "framer-v-cu9pz0",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const convertFromEnum = (value, activeLocale) => {
  switch (value) {
    case "fdKvvD3dw":
      return "W6y1GIkBT";
    case "k_rjxTyKi":
      return "PTEm0r7OH";
    default:
      return "OBjAt4_OD";
  }
};
const convertFromEnum1 = (value, activeLocale) => {
  switch (value) {
    case "fdKvvD3dw":
      return true;
    case "k_rjxTyKi":
      return false;
    default:
      return true;
  }
};
const toBoolean = (value) => {
  return Boolean(value);
};
const transition2 = {
  damping: 14,
  delay: 0,
  mass: 1,
  stiffness: 140,
  type: "spring",
};
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.75,
  skewX: 0,
  skewY: 0,
  transformPerspective: 1200,
  transition: transition2,
  x: 32,
  y: 27,
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transformPerspective: 1200,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.75,
  skewX: 0,
  skewY: 0,
  transformPerspective: 1200,
  x: 32,
  y: 27,
};
const animation3 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.75,
  skewX: 0,
  skewY: 0,
  transformPerspective: 1200,
  transition: transition2,
  x: 32,
  y: 10,
};
const animation4 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.75,
  skewX: 0,
  skewY: 0,
  transformPerspective: 1200,
  x: 32,
  y: 10,
};
const Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
  const [visible, setVisible] = useOverlayState({ blockDocumentScrolling });
  return children({
    hide: () => setVisible(false),
    show: () => setVisible(true),
    toggle: () => setVisible(!visible),
    visible: enabled && visible,
  });
};
const convertFromEnum2 = (value, activeLocale) => {
  switch (value) {
    case "fdKvvD3dw":
      return false;
    case "k_rjxTyKi":
      return true;
    default:
      return false;
  }
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableEnumMap = {
  Button: "Vt63b1HZL",
  Default: "CBnNT_cVM",
  Time_Dark: "CeQWXFzpK",
  Time_Light: "fpVehunuq",
  Time: "jdtc6IfdH",
};
const humanReadableEnumMap1 = { Dark: "k_rjxTyKi", Light: "fdKvvD3dw" };
const humanReadableVariantMap = {
  Desktop_Project_Default: "tdBhGfIRW",
  Desktop_Project: "e6RicA5Ai",
  Desktop_Vertical: "pmZTzPtc9",
  Desktop: "v2CwCl_6S",
  Mobile_Project_Default: "L0sdqDSt8",
  Mobile_Project: "gNhJe7Fbj",
  Mobile_Vertical: "pC552Hdl2",
  Mobile: "Qjx7lyGdh",
};
const getProps = ({
  bGVariant,
  defaultVariant,
  height,
  id,
  socialVariant,
  subscribe,
  timeVariant,
  width,
  ...props
}) => {
  var _humanReadableEnumMap_defaultVariant,
    _ref,
    _ref1,
    _humanReadableEnumMap_timeVariant,
    _ref2,
    _ref3,
    _ref4,
    _humanReadableEnumMap1_socialVariant,
    _ref5,
    _ref6,
    _humanReadableVariantMap_props_variant,
    _ref7;
  return {
    ...props,
    dtjgVuN4V:
      (_ref1 =
        (_ref =
          (_humanReadableEnumMap_defaultVariant =
            humanReadableEnumMap[defaultVariant]) !== null &&
          _humanReadableEnumMap_defaultVariant !== void 0
            ? _humanReadableEnumMap_defaultVariant
            : defaultVariant) !== null && _ref !== void 0
          ? _ref
          : props.dtjgVuN4V) !== null && _ref1 !== void 0
        ? _ref1
        : "jdtc6IfdH",
    l2OjqhSRj:
      (_ref3 =
        (_ref2 =
          (_humanReadableEnumMap_timeVariant =
            humanReadableEnumMap[timeVariant]) !== null &&
          _humanReadableEnumMap_timeVariant !== void 0
            ? _humanReadableEnumMap_timeVariant
            : timeVariant) !== null && _ref2 !== void 0
          ? _ref2
          : props.l2OjqhSRj) !== null && _ref3 !== void 0
        ? _ref3
        : "jdtc6IfdH",
    LBh0a0IEB:
      (_ref4 =
        bGVariant !== null && bGVariant !== void 0
          ? bGVariant
          : props.LBh0a0IEB) !== null && _ref4 !== void 0
        ? _ref4
        : "var(--token-8491ba34-a347-4834-a0f6-2ed6a6f0c292, rgb(235, 235, 234))",
    qTXSBARg2:
      (_ref6 =
        (_ref5 =
          (_humanReadableEnumMap1_socialVariant =
            humanReadableEnumMap1[socialVariant]) !== null &&
          _humanReadableEnumMap1_socialVariant !== void 0
            ? _humanReadableEnumMap1_socialVariant
            : socialVariant) !== null && _ref5 !== void 0
          ? _ref5
          : props.qTXSBARg2) !== null && _ref6 !== void 0
        ? _ref6
        : "fdKvvD3dw",
    t4ryDht7l:
      subscribe !== null && subscribe !== void 0 ? subscribe : props.t4ryDht7l,
    variant:
      (_ref7 =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref7 !== void 0
        ? _ref7
        : "v2CwCl_6S",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    t4ryDht7l,
    l2OjqhSRj,
    dtjgVuN4V,
    qTXSBARg2,
    LBh0a0IEB,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "v2CwCl_6S",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const QB6UkYvuv1fkpbvi = ({ overlay, paginationInfo }) =>
    activeVariantCallback(async (...args) => {
      if (t4ryDht7l) {
        const res = await t4ryDht7l(...args);
        if (res === false) return false;
      }
      overlay.show();
    });
  const ref1 = React.useRef(null);
  const isDisplayed = () => {
    if (
      [
        "Qjx7lyGdh",
        "pC552Hdl2",
        "e6RicA5Ai",
        "gNhJe7Fbj",
        "L0sdqDSt8",
      ].includes(baseVariant)
    )
      return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "e6RicA5Ai") return true;
    return false;
  };
  const isDisplayed2 = () => {
    if (
      [
        "pmZTzPtc9",
        "e6RicA5Ai",
        "gNhJe7Fbj",
        "tdBhGfIRW",
        "L0sdqDSt8",
      ].includes(baseVariant)
    )
      return false;
    return true;
  };
  const isDisplayed3 = () => {
    if (
      [
        "pmZTzPtc9",
        "e6RicA5Ai",
        "gNhJe7Fbj",
        "tdBhGfIRW",
        "L0sdqDSt8",
      ].includes(baseVariant)
    )
      return true;
    return false;
  };
  const visible = toBoolean(convertFromEnum1(qTXSBARg2, activeLocale));
  const isDisplayed4 = (value) => {
    if (["Qjx7lyGdh", "pC552Hdl2", "L0sdqDSt8"].includes(baseVariant))
      return true;
    if (baseVariant === "gNhJe7Fbj") return value;
    return false;
  };
  const isDisplayed5 = () => {
    if (baseVariant === "pC552Hdl2") return false;
    return true;
  };
  const isDisplayed6 = () => {
    if (["Qjx7lyGdh", "gNhJe7Fbj", "L0sdqDSt8"].includes(baseVariant))
      return false;
    return true;
  };
  const ref2 = React.useRef(null);
  const ref3 = React.useRef(null);
  const visible1 = toBoolean(convertFromEnum2(qTXSBARg2, activeLocale));
  const isDisplayed7 = (value) => {
    if (baseVariant === "gNhJe7Fbj") return value;
    return false;
  };
  const isDisplayed8 = () => {
    if (baseVariant === "gNhJe7Fbj") return false;
    return true;
  };
  const ref4 = React.useRef(null);
  const ref5 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-cu9pz0",
            className,
            classNames,
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "v2CwCl_6S",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { backgroundColor: "rgba(0, 0, 0, 0)", ...style },
          variants: { gNhJe7Fbj: { backgroundColor: LBh0a0IEB } },
          ...addPropertyOverrides(
            {
              e6RicA5Ai: { "data-framer-name": "Desktop_Project" },
              gNhJe7Fbj: { "data-framer-name": "Mobile_Project" },
              L0sdqDSt8: { "data-framer-name": "Mobile_Project_Default" },
              pC552Hdl2: { "data-framer-name": "Mobile_Vertical" },
              pmZTzPtc9: { "data-framer-name": "Desktop_Vertical" },
              Qjx7lyGdh: { "data-framer-name": "Mobile" },
              tdBhGfIRW: { "data-framer-name": "Desktop_Project_Default" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            isDisplayed() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-xkf53q-container",
                  layoutDependency: layoutDependency,
                  layoutId: "PUiAm7qlP-container",
                  children: /*#__PURE__*/ _jsx(
                    SocialAdaptiveBarSocial_VisibilityWithMappedReactPropst64o6r,
                    {
                      height: "100%",
                      id: "PUiAm7qlP",
                      layoutId: "PUiAm7qlP",
                      style: { height: "100%" },
                      variant: "OBjAt4_OD",
                      width: "100%",
                      ...addPropertyOverrides(
                        { tdBhGfIRW: { variant: "W6y1GIkBT" } },
                        baseVariant,
                        gestureVariant,
                      ),
                    },
                  ),
                }),
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-k3bbv2-container",
                  "data-framer-name": "Social/ProjectTheme",
                  layoutDependency: layoutDependency,
                  layoutId: "wZxWD9ASu-container",
                  name: "Social/ProjectTheme",
                  children: /*#__PURE__*/ _jsx(SocialAdaptiveBar, {
                    height: "100%",
                    id: "wZxWD9ASu",
                    layoutId: "wZxWD9ASu",
                    name: "Social/ProjectTheme",
                    style: { height: "100%" },
                    variant: convertFromEnum(qTXSBARg2, activeLocale),
                    width: "100%",
                  }),
                }),
              }),
            isDisplayed2() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-aaohzq-container",
                  layoutDependency: layoutDependency,
                  layoutId: "b2nOkLLrQ-container",
                  children: /*#__PURE__*/ _jsx(
                    HomeFooterCornerBackTop_VisibilityWithMappedReactPropsrq5dlk,
                    {
                      height: "100%",
                      id: "b2nOkLLrQ",
                      layoutId: "b2nOkLLrQ",
                      variant: "CBnNT_cVM",
                      width: "100%",
                      ...addPropertyOverrides(
                        {
                          pC552Hdl2: { variant: "Vt63b1HZL" },
                          Qjx7lyGdh: { variant: "Vt63b1HZL" },
                        },
                        baseVariant,
                        gestureVariant,
                      ),
                    },
                  ),
                }),
              }),
            isDisplayed3() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-28lqvw-container",
                  layoutDependency: layoutDependency,
                  layoutId: "eoNud8Xsq-container",
                  children: /*#__PURE__*/ _jsx(HomeFooterCorner, {
                    height: "100%",
                    id: "eoNud8Xsq",
                    layoutId: "eoNud8Xsq",
                    variant: "Vt63b1HZL",
                    width: "100%",
                    ...addPropertyOverrides(
                      {
                        e6RicA5Ai: { variant: l2OjqhSRj },
                        gNhJe7Fbj: { variant: l2OjqhSRj },
                        L0sdqDSt8: { variant: dtjgVuN4V },
                        tdBhGfIRW: { variant: dtjgVuN4V },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                }),
              }),
            isDisplayed4(visible) &&
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-18x0uff",
                "data-framer-name": "Mobile_Light",
                layoutDependency: layoutDependency,
                layoutId: "PAxOgEkAs",
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    width: "54px",
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-u57qdn-container",
                      layoutDependency: layoutDependency,
                      layoutId: "ch71ONbin-container",
                      children: /*#__PURE__*/ _jsx(
                        ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                        {
                          b1BqfRpNR: true,
                          bUFcBjj2_: false,
                          dIiBtQnYe: 100,
                          height: "100%",
                          id: "ch71ONbin",
                          layoutId: "ch71ONbin",
                          style: { height: "100%", width: "100%" },
                          variant: "n7p8bWC6m",
                          VTdF3jUde:
                            "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                          width: "100%",
                          ZWLrRxtcU: true,
                          ...addPropertyOverrides(
                            {
                              gNhJe7Fbj: {
                                jmykv9nju: "https://twitter.com/jayzhushi",
                              },
                              L0sdqDSt8: {
                                jmykv9nju: "https://twitter.com/jayzhushi",
                              },
                              pC552Hdl2: {
                                jmykv9nju: "https://twitter.com/jayzhushi",
                              },
                              Qjx7lyGdh: {
                                jmykv9nju: "https://twitter.com/jayzhushi",
                              },
                            },
                            baseVariant,
                            gestureVariant,
                          ),
                        },
                      ),
                    }),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    width: "54px",
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-2nc1fz-container",
                      layoutDependency: layoutDependency,
                      layoutId: "aCr6pvS8_-container",
                      children: /*#__PURE__*/ _jsx(
                        ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                        {
                          b1BqfRpNR: true,
                          bUFcBjj2_: false,
                          dIiBtQnYe: 100,
                          height: "100%",
                          id: "aCr6pvS8_",
                          layoutId: "aCr6pvS8_",
                          style: { height: "100%", width: "100%" },
                          variant: "PWFVUVWOQ",
                          VTdF3jUde:
                            "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                          width: "100%",
                          ZWLrRxtcU: true,
                          ...addPropertyOverrides(
                            {
                              gNhJe7Fbj: {
                                jmykv9nju:
                                  "https://www.instagram.com/jayzhushi/",
                                variant: "dBXxDpGg9",
                              },
                              L0sdqDSt8: {
                                jmykv9nju:
                                  "https://www.instagram.com/jayzhushi/",
                                variant: "dBXxDpGg9",
                              },
                              pC552Hdl2: {
                                jmykv9nju:
                                  "https://www.instagram.com/jayzhushi/",
                                variant: "dBXxDpGg9",
                              },
                              Qjx7lyGdh: {
                                jmykv9nju:
                                  "https://www.instagram.com/jayzhushi/",
                                variant: "dBXxDpGg9",
                              },
                            },
                            baseVariant,
                            gestureVariant,
                          ),
                        },
                      ),
                    }),
                  }),
                  isDisplayed5() &&
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      width: "54px",
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1sli958-container",
                        layoutDependency: layoutDependency,
                        layoutId: "fFs55ypQk-container",
                        children: /*#__PURE__*/ _jsx(
                          ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                          {
                            b1BqfRpNR: true,
                            bUFcBjj2_: false,
                            dIiBtQnYe: 100,
                            height: "100%",
                            id: "fFs55ypQk",
                            layoutId: "fFs55ypQk",
                            style: { height: "100%", width: "100%" },
                            variant: "LqK6hOvsJ",
                            VTdF3jUde:
                              "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                            width: "100%",
                            ZWLrRxtcU: true,
                            ...addPropertyOverrides(
                              {
                                gNhJe7Fbj: {
                                  jmykv9nju: "mailto:jayzhushi@gmail.com",
                                },
                                L0sdqDSt8: {
                                  jmykv9nju: "mailto:jayzhushi@gmail.com",
                                },
                                Qjx7lyGdh: {
                                  jmykv9nju: "mailto:jayzhushi@gmail.com",
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          },
                        ),
                      }),
                    }),
                  isDisplayed6() &&
                    /*#__PURE__*/ _jsx(Overlay, {
                      blockDocumentScrolling: false,
                      children: (overlay) =>
                        /*#__PURE__*/ _jsx(_Fragment, {
                          children: /*#__PURE__*/ _jsx(
                            ComponentViewportProvider,
                            {
                              children: /*#__PURE__*/ _jsxs(motion.div, {
                                className: "framer-1i8ervd-container",
                                id: `${layoutId}-1i8ervd`,
                                layoutDependency: layoutDependency,
                                layoutId: "aouHcFdY5-container",
                                ref: ref2,
                                children: [
                                  /*#__PURE__*/ _jsx(
                                    ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                                    {
                                      b1BqfRpNR: true,
                                      bUFcBjj2_: false,
                                      dIiBtQnYe: 100,
                                      height: "100%",
                                      id: "aouHcFdY5",
                                      layoutId: "aouHcFdY5",
                                      QB6UkYvuv: QB6UkYvuv1fkpbvi({ overlay }),
                                      variant: "wmCubK61d",
                                      VTdF3jUde:
                                        "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                                      width: "100%",
                                      ZWLrRxtcU: true,
                                    },
                                  ),
                                  /*#__PURE__*/ _jsx(AnimatePresence, {
                                    children:
                                      overlay.visible &&
                                      /*#__PURE__*/ _jsx(Floating, {
                                        alignment: "center",
                                        anchorRef: ref2,
                                        className: cx(
                                          serializationHash,
                                          classNames,
                                          ...sharedStyleClassNames,
                                        ),
                                        collisionDetection: false,
                                        "data-framer-portal-id": `${layoutId}-1i8ervd`,
                                        offsetX: -105,
                                        offsetY: -16,
                                        onDismiss: overlay.hide,
                                        placement: "top",
                                        portalSelector: "#overlay",
                                        safeArea: true,
                                        zIndex: 11,
                                        children: /*#__PURE__*/ _jsx(
                                          MotionDivWithFX,
                                          {
                                            __perspectiveFX: false,
                                            __smartComponentFX: true,
                                            __targetOpacity: 1,
                                            animate: animation1,
                                            className: "framer-1joau5v",
                                            exit: animation,
                                            initial: animation2,
                                            layoutDependency: layoutDependency,
                                            layoutId: "bdQb6serq",
                                            ref: ref3,
                                            role: "dialog",
                                            style: {
                                              backgroundColor:
                                                "rgb(255, 255, 255)",
                                              borderBottomLeftRadius: 24,
                                              borderBottomRightRadius: 24,
                                              borderTopLeftRadius: 24,
                                              borderTopRightRadius: 24,
                                              boxShadow:
                                                "0px 10px 20px 0px rgba(0,0,0,0.05)",
                                              transformPerspective: 1200,
                                            },
                                            variants: {
                                              pC552Hdl2: { boxShadow: "none" },
                                            },
                                            ...addPropertyOverrides(
                                              {
                                                pC552Hdl2: {
                                                  exit: animation3,
                                                  initial: animation4,
                                                },
                                              },
                                              baseVariant,
                                              gestureVariant,
                                            ),
                                            children: /*#__PURE__*/ _jsxs(
                                              motion.div,
                                              {
                                                className: "framer-1vpb7p2",
                                                "data-framer-name": "Notify",
                                                layoutDependency:
                                                  layoutDependency,
                                                layoutId: "oCJHxPQm0",
                                                style: {
                                                  backgroundColor:
                                                    "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                                                  borderBottomLeftRadius: 20,
                                                  borderBottomRightRadius: 20,
                                                  borderTopLeftRadius: 20,
                                                  borderTopRightRadius: 20,
                                                },
                                                children: [
                                                  /*#__PURE__*/ _jsxs(
                                                    motion.div,
                                                    {
                                                      className:
                                                        "framer-1b98n9j",
                                                      layoutDependency:
                                                        layoutDependency,
                                                      layoutId: "LZLVCt0VS",
                                                      children: [
                                                        /*#__PURE__*/ _jsx(
                                                          RichText,
                                                          {
                                                            __fromCanvasComponent: true,
                                                            children:
                                                              /*#__PURE__*/ _jsx(
                                                                React.Fragment,
                                                                {
                                                                  children:
                                                                    /*#__PURE__*/ _jsx(
                                                                      motion.p,
                                                                      {
                                                                        className:
                                                                          "framer-styles-preset-1wxnimg",
                                                                        "data-styles-preset":
                                                                          "tvtD0bAK1",
                                                                        children:
                                                                          "Newsletter",
                                                                      },
                                                                    ),
                                                                },
                                                              ),
                                                            className:
                                                              "framer-be6m0f",
                                                            fonts: ["Inter"],
                                                            layoutDependency:
                                                              layoutDependency,
                                                            layoutId:
                                                              "c3qWEBkHL",
                                                            style: {
                                                              "--framer-link-text-color":
                                                                "rgb(0, 153, 255)",
                                                              "--framer-link-text-decoration":
                                                                "underline",
                                                            },
                                                            verticalAlignment:
                                                              "top",
                                                            withExternalLayout: true,
                                                          },
                                                        ),
                                                        /*#__PURE__*/ _jsx(
                                                          RichText,
                                                          {
                                                            __fromCanvasComponent: true,
                                                            children:
                                                              /*#__PURE__*/ _jsx(
                                                                React.Fragment,
                                                                {
                                                                  children:
                                                                    /*#__PURE__*/ _jsx(
                                                                      motion.p,
                                                                      {
                                                                        className:
                                                                          "framer-styles-preset-9jlebu",
                                                                        "data-styles-preset":
                                                                          "sSyE5_N0_",
                                                                        style: {
                                                                          "--framer-text-color":
                                                                            "var(--extracted-r6o4lv, var(--token-cb5833a4-e810-427d-93f0-14fa8b4ce0f8, rgba(0, 0, 0, 0.5)))",
                                                                        },
                                                                        children:
                                                                          "Get my latest news.",
                                                                      },
                                                                    ),
                                                                },
                                                              ),
                                                            className:
                                                              "framer-16p1vyw",
                                                            fonts: ["Inter"],
                                                            layoutDependency:
                                                              layoutDependency,
                                                            layoutId:
                                                              "T1QTGoPkB",
                                                            style: {
                                                              "--extracted-r6o4lv":
                                                                "var(--token-cb5833a4-e810-427d-93f0-14fa8b4ce0f8, rgba(0, 0, 0, 0.5))",
                                                              "--framer-link-text-color":
                                                                "rgb(0, 153, 255)",
                                                              "--framer-link-text-decoration":
                                                                "underline",
                                                            },
                                                            verticalAlignment:
                                                              "top",
                                                            withExternalLayout: true,
                                                          },
                                                        ),
                                                      ],
                                                    },
                                                  ),
                                                  /*#__PURE__*/ _jsx(
                                                    ComponentViewportProvider,
                                                    {
                                                      children:
                                                        /*#__PURE__*/ _jsx(
                                                          motion.div,
                                                          {
                                                            className:
                                                              "framer-53toz7-container",
                                                            layoutDependency:
                                                              layoutDependency,
                                                            layoutId:
                                                              "ompoVKbz6-container",
                                                            children:
                                                              /*#__PURE__*/ _jsx(
                                                                Mailchimp,
                                                                {
                                                                  borderRadius: 12,
                                                                  bottomLeftRadius: 12,
                                                                  bottomRightRadius: 12,
                                                                  button: {
                                                                    color:
                                                                      "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                                                                    fill: "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                                                                    fontWeight: 600,
                                                                    label:
                                                                      "Sign Up",
                                                                  },
                                                                  font: true,
                                                                  fontFamily:
                                                                    "Satoshi",
                                                                  fontSize: 16,
                                                                  fontWeight: 500,
                                                                  gap: 10,
                                                                  height:
                                                                    "100%",
                                                                  id: "ompoVKbz6",
                                                                  input: {
                                                                    color:
                                                                      "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                                                                    error:
                                                                      "rgb(238, 68, 68)",
                                                                    fill: "var(--token-f940326c-dd8d-431e-94df-2f567f90411e, rgba(0, 0, 0, 0.05))",
                                                                    placeholder:
                                                                      "email@framer.com",
                                                                    placeholderColor:
                                                                      "var(--token-5e69cc31-fdee-4167-b061-faf4cad5053f, rgba(0, 0, 0, 0.3))",
                                                                    value: "",
                                                                  },
                                                                  isMixedBorderRadius: false,
                                                                  layout:
                                                                    "vertical",
                                                                  layoutId:
                                                                    "ompoVKbz6",
                                                                  padding: 15,
                                                                  paddingBottom: 12,
                                                                  paddingLeft: 12,
                                                                  paddingPerSide: true,
                                                                  paddingRight: 12,
                                                                  paddingTop: 12,
                                                                  style: {
                                                                    width:
                                                                      "100%",
                                                                  },
                                                                  topLeftRadius: 12,
                                                                  topRightRadius: 12,
                                                                  url: "https://design.us12.list-manage.com/subscribe/post?u=db06200cf4fc08d5fa6df3cf0&amp;id=cd51730192&amp;f_id=00eaaee0f0",
                                                                  width: "100%",
                                                                },
                                                              ),
                                                          },
                                                        ),
                                                    },
                                                  ),
                                                ],
                                              },
                                            ),
                                          },
                                        ),
                                      }),
                                  }),
                                ],
                              }),
                            },
                          ),
                        }),
                    }),
                ],
              }),
            isDisplayed7(visible1) &&
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1cbummt",
                "data-framer-name": "Mobile_Dark",
                layoutDependency: layoutDependency,
                layoutId: "xYfIdsZlt",
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    width: "54px",
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1ew2i50-container",
                      layoutDependency: layoutDependency,
                      layoutId: "FFBMTaNeo-container",
                      children: /*#__PURE__*/ _jsx(
                        ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                        {
                          b1BqfRpNR: true,
                          bUFcBjj2_: false,
                          dIiBtQnYe: 100,
                          height: "100%",
                          id: "FFBMTaNeo",
                          jmykv9nju: "https://twitter.com/jayzhushi",
                          layoutId: "FFBMTaNeo",
                          style: { height: "100%", width: "100%" },
                          variant: "NgHSBu1eL",
                          VTdF3jUde:
                            "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                          width: "100%",
                          ZWLrRxtcU: true,
                        },
                      ),
                    }),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    width: "54px",
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1s51x9g-container",
                      layoutDependency: layoutDependency,
                      layoutId: "avf4pXf24-container",
                      children: /*#__PURE__*/ _jsx(
                        ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                        {
                          b1BqfRpNR: true,
                          bUFcBjj2_: false,
                          dIiBtQnYe: 100,
                          height: "100%",
                          id: "avf4pXf24",
                          jmykv9nju: "https://www.instagram.com/jayzhushi/",
                          layoutId: "avf4pXf24",
                          style: { height: "100%", width: "100%" },
                          variant: "nBObGXSQT",
                          VTdF3jUde:
                            "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                          width: "100%",
                          ZWLrRxtcU: true,
                        },
                      ),
                    }),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    width: "54px",
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1am75y3-container",
                      layoutDependency: layoutDependency,
                      layoutId: "AEUbFEpgP-container",
                      children: /*#__PURE__*/ _jsx(
                        ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                        {
                          b1BqfRpNR: true,
                          bUFcBjj2_: false,
                          dIiBtQnYe: 100,
                          height: "100%",
                          id: "AEUbFEpgP",
                          jmykv9nju: "mailto:jayzhushi@gmail.com",
                          layoutId: "AEUbFEpgP",
                          style: { height: "100%", width: "100%" },
                          variant: "Kl68LqE9j",
                          VTdF3jUde:
                            "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                          width: "100%",
                          ZWLrRxtcU: true,
                        },
                      ),
                    }),
                  }),
                  isDisplayed8() &&
                    /*#__PURE__*/ _jsx(Overlay, {
                      blockDocumentScrolling: false,
                      children: (overlay1) =>
                        /*#__PURE__*/ _jsx(_Fragment, {
                          children: /*#__PURE__*/ _jsx(
                            ComponentViewportProvider,
                            {
                              children: /*#__PURE__*/ _jsxs(motion.div, {
                                className: "framer-o95cf4-container",
                                id: `${layoutId}-o95cf4`,
                                layoutDependency: layoutDependency,
                                layoutId: "VS7mKdIAR-container",
                                ref: ref4,
                                children: [
                                  /*#__PURE__*/ _jsx(
                                    ButtonContactEffect_MagicHoverWithMappedReactProps1b4od06,
                                    {
                                      b1BqfRpNR: true,
                                      bUFcBjj2_: false,
                                      dIiBtQnYe: 100,
                                      height: "100%",
                                      id: "VS7mKdIAR",
                                      layoutId: "VS7mKdIAR",
                                      QB6UkYvuv: QB6UkYvuv1fkpbvi({
                                        overlay: overlay1,
                                      }),
                                      variant: "wmCubK61d",
                                      VTdF3jUde:
                                        "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                                      width: "100%",
                                      ZWLrRxtcU: true,
                                    },
                                  ),
                                  /*#__PURE__*/ _jsx(AnimatePresence, {
                                    children:
                                      overlay1.visible &&
                                      /*#__PURE__*/ _jsx(Floating, {
                                        alignment: "center",
                                        anchorRef: ref4,
                                        className: cx(
                                          serializationHash,
                                          classNames,
                                          ...sharedStyleClassNames,
                                        ),
                                        collisionDetection: false,
                                        "data-framer-portal-id": `${layoutId}-o95cf4`,
                                        offsetX: -105,
                                        offsetY: -16,
                                        onDismiss: overlay1.hide,
                                        placement: "top",
                                        portalSelector: "#overlay",
                                        safeArea: true,
                                        zIndex: 11,
                                        children: /*#__PURE__*/ _jsx(
                                          MotionDivWithFX,
                                          {
                                            __perspectiveFX: false,
                                            __smartComponentFX: true,
                                            __targetOpacity: 1,
                                            animate: animation1,
                                            className: "framer-1brhs1z",
                                            exit: animation3,
                                            initial: animation4,
                                            layoutDependency: layoutDependency,
                                            layoutId: "fgmJoUxif",
                                            ref: ref5,
                                            role: "dialog",
                                            style: {
                                              backgroundColor:
                                                "rgb(255, 255, 255)",
                                              borderBottomLeftRadius: 24,
                                              borderBottomRightRadius: 24,
                                              borderTopLeftRadius: 24,
                                              borderTopRightRadius: 24,
                                              transformPerspective: 1200,
                                            },
                                            children: /*#__PURE__*/ _jsxs(
                                              motion.div,
                                              {
                                                className: "framer-ur83s9",
                                                "data-framer-name": "Notify",
                                                layoutDependency:
                                                  layoutDependency,
                                                layoutId: "NwoRg4bs4",
                                                style: {
                                                  backgroundColor:
                                                    "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                                                  borderBottomLeftRadius: 20,
                                                  borderBottomRightRadius: 20,
                                                  borderTopLeftRadius: 20,
                                                  borderTopRightRadius: 20,
                                                },
                                                children: [
                                                  /*#__PURE__*/ _jsxs(
                                                    motion.div,
                                                    {
                                                      className:
                                                        "framer-c5mmj2",
                                                      layoutDependency:
                                                        layoutDependency,
                                                      layoutId: "l8dbowH5U",
                                                      children: [
                                                        /*#__PURE__*/ _jsx(
                                                          RichText,
                                                          {
                                                            __fromCanvasComponent: true,
                                                            children:
                                                              /*#__PURE__*/ _jsx(
                                                                React.Fragment,
                                                                {
                                                                  children:
                                                                    /*#__PURE__*/ _jsx(
                                                                      motion.p,
                                                                      {
                                                                        className:
                                                                          "framer-styles-preset-1wxnimg",
                                                                        "data-styles-preset":
                                                                          "tvtD0bAK1",
                                                                        children:
                                                                          "Newsletter",
                                                                      },
                                                                    ),
                                                                },
                                                              ),
                                                            className:
                                                              "framer-1ezcbyq",
                                                            fonts: ["Inter"],
                                                            layoutDependency:
                                                              layoutDependency,
                                                            layoutId:
                                                              "YJXnU4JBu",
                                                            style: {
                                                              "--framer-link-text-color":
                                                                "rgb(0, 153, 255)",
                                                              "--framer-link-text-decoration":
                                                                "underline",
                                                            },
                                                            verticalAlignment:
                                                              "top",
                                                            withExternalLayout: true,
                                                          },
                                                        ),
                                                        /*#__PURE__*/ _jsx(
                                                          RichText,
                                                          {
                                                            __fromCanvasComponent: true,
                                                            children:
                                                              /*#__PURE__*/ _jsx(
                                                                React.Fragment,
                                                                {
                                                                  children:
                                                                    /*#__PURE__*/ _jsx(
                                                                      motion.p,
                                                                      {
                                                                        className:
                                                                          "framer-styles-preset-9jlebu",
                                                                        "data-styles-preset":
                                                                          "sSyE5_N0_",
                                                                        style: {
                                                                          "--framer-text-color":
                                                                            "var(--extracted-r6o4lv, var(--token-cb5833a4-e810-427d-93f0-14fa8b4ce0f8, rgba(0, 0, 0, 0.5)))",
                                                                        },
                                                                        children:
                                                                          "Get my latest news.",
                                                                      },
                                                                    ),
                                                                },
                                                              ),
                                                            className:
                                                              "framer-1th09l7",
                                                            fonts: ["Inter"],
                                                            layoutDependency:
                                                              layoutDependency,
                                                            layoutId:
                                                              "lTJD9uZ4r",
                                                            style: {
                                                              "--extracted-r6o4lv":
                                                                "var(--token-cb5833a4-e810-427d-93f0-14fa8b4ce0f8, rgba(0, 0, 0, 0.5))",
                                                              "--framer-link-text-color":
                                                                "rgb(0, 153, 255)",
                                                              "--framer-link-text-decoration":
                                                                "underline",
                                                            },
                                                            verticalAlignment:
                                                              "top",
                                                            withExternalLayout: true,
                                                          },
                                                        ),
                                                      ],
                                                    },
                                                  ),
                                                  /*#__PURE__*/ _jsx(
                                                    ComponentViewportProvider,
                                                    {
                                                      children:
                                                        /*#__PURE__*/ _jsx(
                                                          motion.div,
                                                          {
                                                            className:
                                                              "framer-1qts6n1-container",
                                                            layoutDependency:
                                                              layoutDependency,
                                                            layoutId:
                                                              "jGLrN2bLR-container",
                                                            children:
                                                              /*#__PURE__*/ _jsx(
                                                                Mailchimp,
                                                                {
                                                                  borderRadius: 12,
                                                                  bottomLeftRadius: 12,
                                                                  bottomRightRadius: 12,
                                                                  button: {
                                                                    color:
                                                                      "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                                                                    fill: "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                                                                    fontWeight: 600,
                                                                    label:
                                                                      "Sign Up",
                                                                  },
                                                                  font: true,
                                                                  fontFamily:
                                                                    "Satoshi",
                                                                  fontSize: 16,
                                                                  fontWeight: 500,
                                                                  gap: 10,
                                                                  height:
                                                                    "100%",
                                                                  id: "jGLrN2bLR",
                                                                  input: {
                                                                    color:
                                                                      "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                                                                    error:
                                                                      "rgb(238, 68, 68)",
                                                                    fill: "var(--token-f940326c-dd8d-431e-94df-2f567f90411e, rgba(0, 0, 0, 0.05))",
                                                                    placeholder:
                                                                      "email@framer.com",
                                                                    placeholderColor:
                                                                      "var(--token-5e69cc31-fdee-4167-b061-faf4cad5053f, rgba(0, 0, 0, 0.3))",
                                                                    value: "",
                                                                  },
                                                                  isMixedBorderRadius: false,
                                                                  layout:
                                                                    "vertical",
                                                                  layoutId:
                                                                    "jGLrN2bLR",
                                                                  padding: 15,
                                                                  paddingBottom: 12,
                                                                  paddingLeft: 12,
                                                                  paddingPerSide: true,
                                                                  paddingRight: 12,
                                                                  paddingTop: 12,
                                                                  style: {
                                                                    width:
                                                                      "100%",
                                                                  },
                                                                  topLeftRadius: 12,
                                                                  topRightRadius: 12,
                                                                  url: "https://design.us12.list-manage.com/subscribe/post?u=db06200cf4fc08d5fa6df3cf0&amp;id=cd51730192&amp;f_id=00eaaee0f0",
                                                                  width: "100%",
                                                                },
                                                              ),
                                                          },
                                                        ),
                                                    },
                                                  ),
                                                ],
                                              },
                                            ),
                                          },
                                        ),
                                      }),
                                  }),
                                ],
                              }),
                            },
                          ),
                        }),
                    }),
                ],
              }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1xl6uza-container",
                layoutDependency: layoutDependency,
                layoutId: "d03TOxXjl-container",
                style: { opacity: 0 },
                children: /*#__PURE__*/ _jsx(SoundPicker, {
                  about:
                    "https://framerusercontent.com/assets/JS0F0ykew7pBc1YLi9C2thx3lA.mp3",
                  click1:
                    "https://framerusercontent.com/assets/NeKEEECpDCUc4QSkjqmTdXLH5GU.mp3",
                  click2:
                    "https://framerusercontent.com/assets/PSUayyGR1zh59jVTvXq7dxzaBs.mp3",
                  click3:
                    "https://framerusercontent.com/assets/tF3exK591Ks2e3NJI0f2jo9XAo.mp3",
                  click4:
                    "https://framerusercontent.com/assets/gVljopYYjzrVbUeGt3La9cq6I4.mp3",
                  height: "100%",
                  hover1:
                    "https://framerusercontent.com/assets/v5V8b74xkcFoD7azK05De3Q2U.mp3",
                  id: "d03TOxXjl",
                  layoutId: "d03TOxXjl",
                  lock: "https://framerusercontent.com/assets/0YxScnd9tCQhXY6WCagHpZm4v8.mp3",
                  popup:
                    "https://framerusercontent.com/assets/upVw7x9UcdCQOnE4UHaGAqt4mM.mp3",
                  slide:
                    "https://framerusercontent.com/assets/Tzsjxn4Nj6hopuN7zbtTykw2C34.mp3",
                  soundon:
                    "https://framerusercontent.com/assets/nBau36Lg0YjnLNUZ4mHwRUnrY.mp3",
                  swoosh:
                    "https://framerusercontent.com/assets/SrckkKlgThNSPqJvnvJrwWMroAw.mp3",
                  unlock:
                    "https://framerusercontent.com/assets/1e9NlcWONVxoxBiQ4ZHyYatDPHI.mp3",
                  width: "100%",
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-8RpJg.framer-1z84j9, .framer-8RpJg .framer-1z84j9 { display: block; }",
  ".framer-8RpJg.framer-cu9pz0 { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 20px 40px 40px 40px; position: relative; width: 1200px; }",
  ".framer-8RpJg .framer-xkf53q-container, .framer-8RpJg .framer-k3bbv2-container { flex: none; height: 54px; pointer-events: auto; position: relative; width: auto; z-index: 1; }",
  ".framer-8RpJg .framer-aaohzq-container, .framer-8RpJg .framer-28lqvw-container { flex: none; height: auto; pointer-events: auto; position: relative; width: auto; }",
  ".framer-8RpJg .framer-18x0uff { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; pointer-events: auto; position: relative; width: min-content; }",
  ".framer-8RpJg .framer-u57qdn-container, .framer-8RpJg .framer-2nc1fz-container, .framer-8RpJg .framer-1sli958-container, .framer-8RpJg .framer-1ew2i50-container, .framer-8RpJg .framer-1s51x9g-container, .framer-8RpJg .framer-1am75y3-container { flex: none; height: 54px; position: relative; width: 54px; }",
  ".framer-8RpJg .framer-1i8ervd-container, .framer-8RpJg .framer-o95cf4-container { flex: none; height: auto; position: relative; width: auto; z-index: 0; }",
  ".framer-8RpJg .framer-1joau5v, .framer-8RpJg .framer-1brhs1z { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 266px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-8RpJg .framer-1vpb7p2, .framer-8RpJg .framer-ur83s9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 20px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-8RpJg .framer-1b98n9j, .framer-8RpJg .framer-c5mmj2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 4px; position: relative; width: min-content; }",
  ".framer-8RpJg .framer-be6m0f, .framer-8RpJg .framer-16p1vyw, .framer-8RpJg .framer-1ezcbyq, .framer-8RpJg .framer-1th09l7 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-8RpJg .framer-53toz7-container, .framer-8RpJg .framer-1qts6n1-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-8RpJg .framer-1cbummt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; pointer-events: auto; position: relative; width: min-content; }",
  ".framer-8RpJg .framer-1xl6uza-container { bottom: 20px; flex: none; height: auto; pointer-events: none; position: absolute; right: 20px; width: auto; z-index: 1; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-8RpJg .framer-18x0uff, .framer-8RpJg .framer-1joau5v, .framer-8RpJg .framer-1vpb7p2, .framer-8RpJg .framer-1b98n9j, .framer-8RpJg .framer-1cbummt, .framer-8RpJg .framer-1brhs1z, .framer-8RpJg .framer-ur83s9, .framer-8RpJg .framer-c5mmj2 { gap: 0px; } .framer-8RpJg .framer-18x0uff > *, .framer-8RpJg .framer-1joau5v > *, .framer-8RpJg .framer-1brhs1z > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-8RpJg .framer-18x0uff > :first-child, .framer-8RpJg .framer-1joau5v > :first-child, .framer-8RpJg .framer-1cbummt > :first-child, .framer-8RpJg .framer-1brhs1z > :first-child { margin-left: 0px; } .framer-8RpJg .framer-18x0uff > :last-child, .framer-8RpJg .framer-1joau5v > :last-child, .framer-8RpJg .framer-1cbummt > :last-child, .framer-8RpJg .framer-1brhs1z > :last-child { margin-right: 0px; } .framer-8RpJg .framer-1vpb7p2 > *, .framer-8RpJg .framer-ur83s9 > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-8RpJg .framer-1vpb7p2 > :first-child, .framer-8RpJg .framer-1b98n9j > :first-child, .framer-8RpJg .framer-ur83s9 > :first-child, .framer-8RpJg .framer-c5mmj2 > :first-child { margin-top: 0px; } .framer-8RpJg .framer-1vpb7p2 > :last-child, .framer-8RpJg .framer-1b98n9j > :last-child, .framer-8RpJg .framer-ur83s9 > :last-child, .framer-8RpJg .framer-c5mmj2 > :last-child { margin-bottom: 0px; } .framer-8RpJg .framer-1b98n9j > *, .framer-8RpJg .framer-c5mmj2 > * { margin: 0px; margin-bottom: calc(5px / 2); margin-top: calc(5px / 2); } .framer-8RpJg .framer-1cbummt > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } }",
  ".framer-8RpJg.framer-v-tizt5h.framer-cu9pz0 { align-content: center; align-items: center; flex-direction: column; gap: 40px; justify-content: flex-start; padding: 40px 40px 120px 40px; width: 390px; }",
  ".framer-8RpJg.framer-v-tizt5h .framer-aaohzq-container, .framer-8RpJg.framer-v-n56b7x .framer-aaohzq-container, .framer-8RpJg.framer-v-wnqb0w .framer-28lqvw-container { order: 4; }",
  ".framer-8RpJg.framer-v-tizt5h .framer-18x0uff, .framer-8RpJg.framer-v-n56b7x .framer-18x0uff, .framer-8RpJg.framer-v-wnqb0w .framer-18x0uff, .framer-8RpJg.framer-v-1wc2ac0 .framer-18x0uff { gap: 16px; order: 2; }",
  ".framer-8RpJg.framer-v-tizt5h .framer-1xl6uza-container, .framer-8RpJg.framer-v-n56b7x .framer-1xl6uza-container, .framer-8RpJg.framer-v-wnqb0w .framer-1xl6uza-container, .framer-8RpJg.framer-v-1wc2ac0 .framer-1xl6uza-container { order: 6; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-8RpJg.framer-v-tizt5h.framer-cu9pz0, .framer-8RpJg.framer-v-tizt5h .framer-18x0uff { gap: 0px; } .framer-8RpJg.framer-v-tizt5h.framer-cu9pz0 > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-8RpJg.framer-v-tizt5h.framer-cu9pz0 > :first-child { margin-top: 0px; } .framer-8RpJg.framer-v-tizt5h.framer-cu9pz0 > :last-child { margin-bottom: 0px; } .framer-8RpJg.framer-v-tizt5h .framer-18x0uff > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-8RpJg.framer-v-tizt5h .framer-18x0uff > :first-child { margin-left: 0px; } .framer-8RpJg.framer-v-tizt5h .framer-18x0uff > :last-child { margin-right: 0px; } }",
  ".framer-8RpJg.framer-v-n56b7x.framer-cu9pz0, .framer-8RpJg.framer-v-wnqb0w.framer-cu9pz0, .framer-8RpJg.framer-v-1wc2ac0.framer-cu9pz0 { align-content: center; align-items: center; flex-direction: column; gap: 40px; justify-content: flex-start; padding: 40px; width: 390px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-8RpJg.framer-v-n56b7x.framer-cu9pz0, .framer-8RpJg.framer-v-n56b7x .framer-18x0uff { gap: 0px; } .framer-8RpJg.framer-v-n56b7x.framer-cu9pz0 > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-8RpJg.framer-v-n56b7x.framer-cu9pz0 > :first-child { margin-top: 0px; } .framer-8RpJg.framer-v-n56b7x.framer-cu9pz0 > :last-child { margin-bottom: 0px; } .framer-8RpJg.framer-v-n56b7x .framer-18x0uff > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-8RpJg.framer-v-n56b7x .framer-18x0uff > :first-child { margin-left: 0px; } .framer-8RpJg.framer-v-n56b7x .framer-18x0uff > :last-child { margin-right: 0px; } }",
  ".framer-8RpJg.framer-v-wnqb0w .framer-1cbummt, .framer-8RpJg.framer-v-1wc2ac0 .framer-28lqvw-container { order: 3; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-8RpJg.framer-v-wnqb0w.framer-cu9pz0, .framer-8RpJg.framer-v-wnqb0w .framer-18x0uff { gap: 0px; } .framer-8RpJg.framer-v-wnqb0w.framer-cu9pz0 > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-8RpJg.framer-v-wnqb0w.framer-cu9pz0 > :first-child { margin-top: 0px; } .framer-8RpJg.framer-v-wnqb0w.framer-cu9pz0 > :last-child { margin-bottom: 0px; } .framer-8RpJg.framer-v-wnqb0w .framer-18x0uff > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-8RpJg.framer-v-wnqb0w .framer-18x0uff > :first-child { margin-left: 0px; } .framer-8RpJg.framer-v-wnqb0w .framer-18x0uff > :last-child { margin-right: 0px; } }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-8RpJg.framer-v-1wc2ac0.framer-cu9pz0, .framer-8RpJg.framer-v-1wc2ac0 .framer-18x0uff { gap: 0px; } .framer-8RpJg.framer-v-1wc2ac0.framer-cu9pz0 > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-8RpJg.framer-v-1wc2ac0.framer-cu9pz0 > :first-child { margin-top: 0px; } .framer-8RpJg.framer-v-1wc2ac0.framer-cu9pz0 > :last-child { margin-bottom: 0px; } .framer-8RpJg.framer-v-1wc2ac0 .framer-18x0uff > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-8RpJg.framer-v-1wc2ac0 .framer-18x0uff > :first-child { margin-left: 0px; } .framer-8RpJg.framer-v-1wc2ac0 .framer-18x0uff > :last-child { margin-right: 0px; } }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 114
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Qjx7lyGdh":{"layout":["fixed","auto"]},"pmZTzPtc9":{"layout":["fixed","auto"]},"pC552Hdl2":{"layout":["fixed","auto"]},"e6RicA5Ai":{"layout":["fixed","auto"]},"gNhJe7Fbj":{"layout":["fixed","auto"]},"tdBhGfIRW":{"layout":["fixed","auto"]},"L0sdqDSt8":{"layout":["fixed","auto"]}}}
 * @framerVariables {"t4ryDht7l":"subscribe","l2OjqhSRj":"timeVariant","dtjgVuN4V":"defaultVariant","qTXSBARg2":"socialVariant","LBh0a0IEB":"bGVariant"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const Framerih_RAIMJP = withCSS(Component, css, "framer-8RpJg");
export default Framerih_RAIMJP;
Framerih_RAIMJP.displayName = "Home/Footer";
Framerih_RAIMJP.defaultProps = { height: 114, width: 1200 };
addPropertyControls(Framerih_RAIMJP, {
  variant: {
    options: [
      "v2CwCl_6S",
      "Qjx7lyGdh",
      "pmZTzPtc9",
      "pC552Hdl2",
      "e6RicA5Ai",
      "gNhJe7Fbj",
      "tdBhGfIRW",
      "L0sdqDSt8",
    ],
    optionTitles: [
      "Desktop",
      "Mobile",
      "Desktop_Vertical",
      "Mobile_Vertical",
      "Desktop_Project",
      "Mobile_Project",
      "Desktop_Project_Default",
      "Mobile_Project_Default",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  t4ryDht7l: { title: "Subscribe", type: ControlType.EventHandler },
  l2OjqhSRj: (HomeFooterCornerControls === null ||
  HomeFooterCornerControls === void 0
    ? void 0
    : HomeFooterCornerControls["variant"]) && {
    ...HomeFooterCornerControls["variant"],
    defaultValue: "jdtc6IfdH",
    description: undefined,
    hidden: undefined,
    title: "Time Variant",
  },
  dtjgVuN4V: (HomeFooterCornerControls === null ||
  HomeFooterCornerControls === void 0
    ? void 0
    : HomeFooterCornerControls["variant"]) && {
    ...HomeFooterCornerControls["variant"],
    defaultValue: "jdtc6IfdH",
    description: undefined,
    hidden: undefined,
    title: "Default Variant",
  },
  qTXSBARg2: {
    defaultValue: "fdKvvD3dw",
    options: ["fdKvvD3dw", "k_rjxTyKi"],
    optionTitles: ["Light", "Dark"],
    title: "Social Variant",
    type: ControlType.Enum,
  },
  LBh0a0IEB: {
    defaultValue:
      'var(--token-8491ba34-a347-4834-a0f6-2ed6a6f0c292, rgb(235, 235, 234)) /* {"name":"Backdrop"} */',
    title: "BG Variant",
    type: ControlType.Color,
  },
});
addFonts(
  Framerih_RAIMJP,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
          weight: "400",
        },
      ],
    },
    ...SocialAdaptiveBarFonts,
    ...HomeFooterCornerFonts,
    ...ButtonContactFonts,
    ...MailchimpFonts,
    ...SoundPickerFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerih_RAIMJP",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Qjx7lyGdh":{"layout":["fixed","auto"]},"pmZTzPtc9":{"layout":["fixed","auto"]},"pC552Hdl2":{"layout":["fixed","auto"]},"e6RicA5Ai":{"layout":["fixed","auto"]},"gNhJe7Fbj":{"layout":["fixed","auto"]},"tdBhGfIRW":{"layout":["fixed","auto"]},"L0sdqDSt8":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "114",
        framerIntrinsicWidth: "1200",
        framerVariables:
          '{"t4ryDht7l":"subscribe","l2OjqhSRj":"timeVariant","dtjgVuN4V":"defaultVariant","qTXSBARg2":"socialVariant","LBh0a0IEB":"bGVariant"}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
