// Generated by Framer (b12dec4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  cx,
  SVG,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Animate_ArrowKey } from "https://framerusercontent.com/modules/kLa7qiYA4dfsdQ7XGm00/YD1twedwd956Done8Gic/Utilities.js";
const MotionDivAnimate_ArrowKey = Animate_ArrowKey(motion.div);
const cycleOrder = ["QJF9A9kA2"];
const variantClassNames = { QJF9A9kA2: "framer-v-5p5l6j" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transitions = {
  default: { delay: 0, duration: 0.2, ease: [0.44, 0, 0.56, 1], type: "tween" },
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) =>
  variants.join("-") + props.layoutDependency;
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    gestureVariant,
    setGestureState,
    setVariant,
    transition,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "QJF9A9kA2",
    transitions,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const defaultLayoutId = React.useId();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(motion.div, {
      initial: variant,
      animate: variants,
      onHoverStart: () => setGestureState({ isHovered: true }),
      onHoverEnd: () => setGestureState({ isHovered: false }),
      onTapStart: () => setGestureState({ isPressed: true }),
      onTap: () => setGestureState({ isPressed: false }),
      onTapCancel: () => setGestureState({ isPressed: false }),
      className: cx("framer-dJXBY", classNames),
      style: { display: "contents" },
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          className: cx("framer-5p5l6j", className),
          "data-framer-name": "Up",
          layoutDependency: layoutDependency,
          layoutId: "QJF9A9kA2",
          ref: ref,
          style: { ...style },
          children: /*#__PURE__*/ _jsxs(MotionDivAnimate_ArrowKey, {
            className: "framer-kj0kde",
            layoutDependency: layoutDependency,
            layoutId: "HHu6gXLk8",
            children: [
              /*#__PURE__*/ _jsx(SVG, {
                className: "framer-1bwdedv",
                "data-framer-name": "scissor_rectangle",
                layout: "position",
                layoutDependency: layoutDependency,
                layoutId: "KcF_NDfYq",
                opacity: 1,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 30 30"><path d="M 5 15 C 5 10.286 5 7.928 6.464 6.464 C 7.928 5 10.285 5 15 5 C 19.714 5 22.072 5 23.536 6.464 C 25 7.928 25 10.285 25 15 C 25 19.714 25 22.072 23.536 23.536 C 22.071 25 19.715 25 15 25 C 10.286 25 7.928 25 6.464 23.536 C 5 22.071 5 19.715 5 15 Z" fill="transparent" stroke-width="1.8" stroke="var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0)) /* {&quot;name&quot;:&quot;Black 100&quot;} */" stroke-miterlimit="10"></path></svg>',
                svgContentId: 3559415441,
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsx(SVG, {
                className: "framer-19ixq5g",
                "data-framer-name": "arrow_left_01_round",
                layout: "position",
                layoutDependency: layoutDependency,
                layoutId: "LOpRdkBzo",
                opacity: 1,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 18 18"><path d="M 11.854 4.055 C 11.608 3.722 11.139 3.651 10.805 3.896 C 10.017 4.482 9.251 5.097 8.508 5.739 C 7.936 6.236 7.345 6.786 6.891 7.3 C 6.664 7.556 6.456 7.821 6.301 8.08 C 6.158 8.316 6 8.642 6 9 C 6 9.357 6.157 9.684 6.301 9.921 C 6.457 10.179 6.664 10.444 6.891 10.7 C 7.345 11.214 7.936 11.765 8.508 12.261 C 9.251 12.903 10.017 13.518 10.805 14.104 C 11.033 14.271 11.336 14.297 11.588 14.169 C 11.841 14.042 12 13.783 12 13.5 L 12 4.5 C 12 4.34 11.949 4.184 11.854 4.055 Z" fill="var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0)) /* {&quot;name&quot;:&quot;Black 100&quot;} */"></path></svg>',
                svgContentId: 648395362,
                withExternalLayout: true,
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  '.framer-dJXBY [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-dJXBY .framer-1kzacl1 { display: block; }",
  ".framer-dJXBY .framer-5p5l6j { height: 42px; position: relative; width: 42px; }",
  ".framer-dJXBY .framer-kj0kde { flex: none; height: 30px; left: calc(50.00000000000002% - 30px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 30px / 2); width: 30px; }",
  ".framer-dJXBY .framer-1bwdedv { flex: none; height: 30px; left: calc(50.00000000000002% - 30px / 2); position: absolute; top: calc(50.00000000000002% - 30px / 2); width: 30px; }",
  ".framer-dJXBY .framer-19ixq5g { flex: none; height: 18px; left: calc(50.00000000000002% - 18px / 2); position: absolute; top: calc(50.00000000000002% - 18px / 2); width: 18px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 42
 * @framerIntrinsicWidth 42
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables false
 */ const FramerkEXaEesTB = withCSS(Component, css, "framer-dJXBY");
export default FramerkEXaEesTB;
FramerkEXaEesTB.displayName = "Button/ArrowKey";
FramerkEXaEesTB.defaultProps = { height: 42, width: 42 };
addFonts(FramerkEXaEesTB, []);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerkEXaEesTB",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "42",
        framerIntrinsicHeight: "42",
        framerContractVersion: "1",
        framerImmutableVariables: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
