// Generated by Framer (7f988a2)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withMappedReactProps,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Layout_Variants_Mobile } from "https://framerusercontent.com/modules/RGCgkyyKvYCOcpgTFJih/l8apYUQ1NMMBi28Mu8sO/Page.js";
import HomeLayouTablet, * as HomeLayouTabletInfo from "https://framerusercontent.com/modules/VmvSKM03ypbC3wkdd7Z1/qR8vr8f6u6hyxvUN5juP/u6uvtxOlk.js";
const HomeLayouTabletFonts = getFonts(HomeLayouTablet);
const HomeLayouTabletLayout_Variants_MobileWithMappedReactProps14xqjvm =
  withMappedReactProps(
    Layout_Variants_Mobile(HomeLayouTablet),
    HomeLayouTabletInfo,
  );
const cycleOrder = ["HmKlmI9F2"];
const serializationHash = "framer-WgzFW";
const variantClassNames = { HmKlmI9F2: "framer-v-wfahwp" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const getProps = ({
  height,
  iconCursor,
  id,
  notice,
  projectCursor,
  width,
  ...props
}) => {
  return {
    ...props,
    hxNeo0OUE:
      projectCursor !== null && projectCursor !== void 0
        ? projectCursor
        : props.hxNeo0OUE,
    mZtE1brt4:
      iconCursor !== null && iconCursor !== void 0
        ? iconCursor
        : props.mZtE1brt4,
    pbuE6UhMj: notice !== null && notice !== void 0 ? notice : props.pbuE6UhMj,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    hxNeo0OUE,
    mZtE1brt4,
    pbuE6UhMj,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    gestureHandlers,
    gestureVariant,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "HmKlmI9F2",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const J6eOx28iq1iy14oh = activeVariantCallback(async (...args) => {
    if (pbuE6UhMj) {
      const res = await pbuE6UhMj(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-wfahwp",
            className,
            classNames,
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "HmKlmI9F2",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            width: `max(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"}, 1px)`,
            children: /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-yge6ts-container",
              layoutDependency: layoutDependency,
              layoutId: "SvF8_Fs7d-container",
              children: /*#__PURE__*/ _jsx(
                HomeLayouTabletLayout_Variants_MobileWithMappedReactProps14xqjvm,
                {
                  d95Uyy9vG: mZtE1brt4,
                  height: "100%",
                  id: "SvF8_Fs7d",
                  J6eOx28iq: J6eOx28iq1iy14oh,
                  layoutId: "SvF8_Fs7d",
                  lxzOuQJFn: hxNeo0OUE,
                  style: { width: "100%" },
                  variant: "mzy8kT2OF",
                  width: "100%",
                },
              ),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-WgzFW.framer-87ywv0, .framer-WgzFW .framer-87ywv0 { display: block; }",
  ".framer-WgzFW.framer-wfahwp { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 810px; }",
  ".framer-WgzFW .framer-yge6ts-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-WgzFW.framer-wfahwp { gap: 0px; } .framer-WgzFW.framer-wfahwp > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-WgzFW.framer-wfahwp > :first-child { margin-left: 0px; } .framer-WgzFW.framer-wfahwp > :last-child { margin-right: 0px; } }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 4429
 * @framerIntrinsicWidth 810
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"hxNeo0OUE":"projectCursor","mZtE1brt4":"iconCursor","pbuE6UhMj":"notice"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramermFk05Wwh7 = withCSS(Component, css, "framer-WgzFW");
export default FramermFk05Wwh7;
FramermFk05Wwh7.displayName = "Home/HeroTablet";
FramermFk05Wwh7.defaultProps = { height: 4429, width: 810 };
addPropertyControls(FramermFk05Wwh7, {
  hxNeo0OUE: { title: "Project Cursor", type: ControlType.CustomCursor },
  mZtE1brt4: { title: "Icon Cursor", type: ControlType.CustomCursor },
  pbuE6UhMj: { title: "Notice", type: ControlType.EventHandler },
});
addFonts(
  FramermFk05Wwh7,
  [{ explicitInter: true, fonts: [] }, ...HomeLayouTabletFonts],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramermFk05Wwh7",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"hxNeo0OUE":"projectCursor","mZtE1brt4":"iconCursor","pbuE6UhMj":"notice"}',
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "4429",
        framerIntrinsicWidth: "810",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
