// Generated by Framer (68f6254)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import Appearence from "https://framerusercontent.com/modules/IkmROXxT6vYQmp2TxMA5/mdpm8d8I8otsEqnAVIgu/Appearence.js";
import {
  Effect_MagicHover,
  Language_Chn_Content,
  Language_En_Content,
} from "https://framerusercontent.com/modules/yue1wEIuxL5Wxj17VKpu/rvoe6u8OOiWRrmZZxev9/Toggle.js";
import * as sharedStyle from "https://framerusercontent.com/modules/IJuPkH75DrOaXa8hMB2D/uNPycaMZJ1T8jriUTsGK/sSyE5_N0_.js";
const AppearenceFonts = getFonts(Appearence);
const RichTextLanguage_En_Content = Language_En_Content(RichText);
const RichTextLanguage_Chn_Content = Language_Chn_Content(RichText);
const MotionDivEffect_MagicHover = Effect_MagicHover(motion.div);
const enabledGestures = {
  bv_kvtKqT: { hover: true },
  eZIUywzZC: { hover: true },
};
const cycleOrder = ["eZIUywzZC", "bv_kvtKqT"];
const serializationHash = "framer-bCcj6";
const variantClassNames = {
  bv_kvtKqT: "framer-v-zww102",
  eZIUywzZC: "framer-v-v5q0ir",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 28,
  delay: 0,
  mass: 1,
  stiffness: 170,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = { Off: "bv_kvtKqT", On: "eZIUywzZC" };
const getProps = ({ height, id, tap, tapA, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    ah1iEr8il: tapA !== null && tapA !== void 0 ? tapA : props.ah1iEr8il,
    K4FXNGAHE: tap !== null && tap !== void 0 ? tap : props.K4FXNGAHE,
    variant:
      (_ref =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref !== void 0
        ? _ref
        : "eZIUywzZC",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    K4FXNGAHE,
    ah1iEr8il,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "eZIUywzZC",
    enabledGestures,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap6di1eq = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (K4FXNGAHE) {
      const res = await K4FXNGAHE(...args);
      if (res === false) return false;
    }
    if (ah1iEr8il) {
      const res = await ah1iEr8il(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [sharedStyle.className];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-v5q0ir",
            className,
            classNames,
          ),
          "data-framer-name": "On",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "eZIUywzZC",
          onTap: onTap6di1eq,
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            backgroundColor:
              "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
            borderBottomLeftRadius: 16,
            borderBottomRightRadius: 16,
            borderTopLeftRadius: 16,
            borderTopRightRadius: 16,
            ...style,
          },
          ...addPropertyOverrides(
            {
              "bv_kvtKqT-hover": { "data-framer-name": undefined },
              "eZIUywzZC-hover": { "data-framer-name": undefined },
              bv_kvtKqT: { "data-framer-name": "Off" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(MotionDivEffect_MagicHover, {
            className: "framer-vhwzac",
            layoutDependency: layoutDependency,
            layoutId: "HWpukEn0k",
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-vmv02j",
                layoutDependency: layoutDependency,
                layoutId: "lBsrkPoZH",
                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  children: /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1fdvxh5-container",
                    layoutDependency: layoutDependency,
                    layoutId: "QuhAjQaJi-container",
                    children: /*#__PURE__*/ _jsx(Appearence, {
                      color:
                        "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                      fill_tap:
                        "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                      fill: "var(--token-b7850564-586d-46b0-98d2-820c4ec87b3f, rgba(255, 255, 255, 0))",
                      height: "100%",
                      hover_color:
                        "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                      hover_effect: false,
                      id: "QuhAjQaJi",
                      layoutId: "QuhAjQaJi",
                      width: "100%",
                    }),
                  }),
                }),
              }),
              /*#__PURE__*/ _jsx(RichTextLanguage_En_Content, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-9jlebu",
                    "data-styles-preset": "sSyE5_N0_",
                    children: "Light",
                  }),
                }),
                className: "framer-vuyiu5",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "jBbba1bAb",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    bv_kvtKqT: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-9jlebu",
                          "data-styles-preset": "sSyE5_N0_",
                          children: "Dark",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
              /*#__PURE__*/ _jsx(RichTextLanguage_Chn_Content, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-9jlebu",
                    "data-styles-preset": "sSyE5_N0_",
                    children: "浅色外观",
                  }),
                }),
                className: "framer-1ans0pn",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "aApVk0T8S",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    bv_kvtKqT: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-9jlebu",
                          "data-styles-preset": "sSyE5_N0_",
                          children: "深色外观",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-bCcj6.framer-1geduup, .framer-bCcj6 .framer-1geduup { display: block; }",
  ".framer-bCcj6.framer-v5q0ir { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 83px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-bCcj6 .framer-vhwzac { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 16px 0px 20px 0px; position: relative; width: 100%; }",
  ".framer-bCcj6 .framer-vmv02j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 36px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 36px; }",
  ".framer-bCcj6 .framer-1fdvxh5-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-bCcj6 .framer-vuyiu5, .framer-bCcj6 .framer-1ans0pn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bCcj6.framer-v5q0ir, .framer-bCcj6 .framer-vhwzac, .framer-bCcj6 .framer-vmv02j { gap: 0px; } .framer-bCcj6.framer-v5q0ir > *, .framer-bCcj6 .framer-vhwzac > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-bCcj6.framer-v5q0ir > :first-child, .framer-bCcj6 .framer-vhwzac > :first-child { margin-top: 0px; } .framer-bCcj6.framer-v5q0ir > :last-child, .framer-bCcj6 .framer-vhwzac > :last-child { margin-bottom: 0px; } .framer-bCcj6 .framer-vmv02j > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-bCcj6 .framer-vmv02j > :first-child { margin-left: 0px; } .framer-bCcj6 .framer-vmv02j > :last-child { margin-right: 0px; } }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 110.5
 * @framerIntrinsicWidth 83
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"bv_kvtKqT":{"layout":["fixed","auto"]},"ektPKnAjP":{"layout":["fixed","auto"]},"TkQYv9WdQ":{"layout":["fixed","auto"]}}}
 * @framerVariables {"K4FXNGAHE":"tap","ah1iEr8il":"tapA"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerOa1j0sIpg = withCSS(Component, css, "framer-bCcj6");
export default FramerOa1j0sIpg;
FramerOa1j0sIpg.displayName = "Toggle/Theme";
FramerOa1j0sIpg.defaultProps = { height: 110.5, width: 83 };
addPropertyControls(FramerOa1j0sIpg, {
  variant: {
    options: ["eZIUywzZC", "bv_kvtKqT"],
    optionTitles: ["On", "Off"],
    title: "Variant",
    type: ControlType.Enum,
  },
  K4FXNGAHE: { title: "Tap", type: ControlType.EventHandler },
  ah1iEr8il: { title: "Tap A", type: ControlType.EventHandler },
});
addFonts(
  FramerOa1j0sIpg,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
          weight: "400",
        },
      ],
    },
    ...AppearenceFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerOa1j0sIpg",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "110.5",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "83",
        framerContractVersion: "1",
        framerVariables: '{"K4FXNGAHE":"tap","ah1iEr8il":"tapA"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"bv_kvtKqT":{"layout":["fixed","auto"]},"ektPKnAjP":{"layout":["fixed","auto"]},"TkQYv9WdQ":{"layout":["fixed","auto"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
