// Generated by Framer (cac55f6)
import { jsx as e } from "react/jsx-runtime";
import {
  addFonts as r,
  cx as t,
  SVG as o,
  useLocaleInfo as a,
  useVariantState as i,
  withCSS as n,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import {
  LayoutGroup as l,
  motion as d,
  MotionConfigContext as s,
} from "framer-motion";
import * as f from "react";
import * as p from "./Q9BYQlEoa-0.js";
let m = ["lQS671WU9"],
  u = "framer-5ZydW",
  c = { lQS671WU9: "framer-v-1jihmzc" };
function h(e, ...r) {
  let t = {};
  return null == r || r.forEach((r) => r && Object.assign(t, e[r])), t;
}
let y = { default: { duration: 0, type: "tween" } },
  b = { YzTqEHveH: p },
  v = (e, r) => {
    for (; r; ) {
      let t = b[r.id];
      if (t) {
        let r = t[e];
        if (r) return r;
      }
      r = r.fallback;
    }
  },
  w = ({ value: r, children: t }) => {
    let o = f.useContext(s),
      a = null != r ? r : o.transition,
      i = f.useMemo(() => ({ ...o, transition: a }), [JSON.stringify(a)]);
    return /*#__PURE__*/ e(s.Provider, { value: i, children: t });
  },
  x = ({ height: e, id: r, width: t, ...o }) => ({ ...o }),
  g = (e, r) => r.join("-") + e.layoutDependency,
  k = /*#__PURE__*/ f.forwardRef(function (r, n) {
    let { activeLocale: s } = a(),
      { style: p, className: u, layoutId: h, variant: b, ...v } = x(r),
      {
        baseVariant: k,
        classNames: W,
        gestureVariant: j,
        setGestureState: S,
        setVariant: Z,
        transition: q,
        variants: H,
      } = i({
        cycleOrder: m,
        defaultVariant: "lQS671WU9",
        transitions: y,
        variant: b,
        variantClassNames: c,
      }),
      Q = g(r, H),
      z = f.useRef(null),
      C = f.useId();
    return /*#__PURE__*/ e(l, {
      id: null != h ? h : C,
      children: /*#__PURE__*/ e(d.div, {
        initial: b,
        animate: H,
        onHoverStart: () => S({ isHovered: !0 }),
        onHoverEnd: () => S({ isHovered: !1 }),
        onTapStart: () => S({ isPressed: !0 }),
        onTap: () => S({ isPressed: !1 }),
        onTapCancel: () => S({ isPressed: !1 }),
        className: t("framer-5ZydW", ...[], W),
        style: { display: "contents" },
        children: /*#__PURE__*/ e(w, {
          value: q,
          children: /*#__PURE__*/ e(d.div, {
            ...v,
            className: t("framer-1jihmzc", u),
            "data-framer-name": "Left",
            layoutDependency: Q,
            layoutId: "lQS671WU9",
            ref: null != n ? n : z,
            style: { ...p },
            children: /*#__PURE__*/ e(o, {
              className: "framer-811bk2",
              "data-framer-name": "arrow_left_01_sharp",
              layout: "position",
              layoutDependency: Q,
              layoutId: "MFR743p8y",
              opacity: 1,
              svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 15 6 L 9.707 11.293 C 9.374 11.626 9.207 11.793 9.207 12 C 9.207 12.207 9.374 12.374 9.707 12.707 L 15 18" fill="transparent" stroke-width="1.8" stroke="var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0)) /* {&quot;name&quot;:&quot;Black 100&quot;} */" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>',
              svgContentId: 1074520109,
              withExternalLayout: !0,
            }),
          }),
        }),
      }),
    });
  }),
  W = [
    '.framer-5ZydW [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
    "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
    ".framer-5ZydW .framer-dqlenb { display: block; }",
    ".framer-5ZydW .framer-1jihmzc { height: 24px; position: relative; width: 24px; }",
    ".framer-5ZydW .framer-811bk2 { flex: none; height: 24px; left: calc(50.00000000000002% - 24px / 2); position: absolute; top: calc(50.00000000000002% - 24px / 2); width: 24px; }",
  ],
  j = n(k, W, "framer-5ZydW");
export default j;
(j.displayName = "Button/ArrowLeft"),
  (j.defaultProps = { height: 24, width: 24 }),
  r(j, []);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerQ9BYQlEoa",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "24",
        framerContractVersion: "1",
        framerIntrinsicHeight: "24",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./Q9BYQlEoa.map
