// Generated by Framer (a7ecdf4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  cx,
  getFonts,
  SVG,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import Arc from "https://framerusercontent.com/modules/4S4SnR1GdEzX95H1h5mT/2ycm7HJhFdePAmCNAAJd/Arc.js";
import * as localizedValues from "./soKmLF9CI-0.js";
const ArcFonts = getFonts(Arc);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["sBbVTkEzY"];
const serializationHash = "framer-vmej5";
const variantClassNames = { sBbVTkEzY: "framer-v-162cfys" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transitions = {
  default: { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" },
};
const valuesByLocaleId = { YzTqEHveH: localizedValues };
const getLocalizedValue = (key, locale) => {
  while (locale) {
    const values = valuesByLocaleId[locale.id];
    if (values) {
      const value = values[key];
      if (value) {
        return value;
      }
    }
    locale = locale.fallback;
  }
};
const transition1 = {
  delay: 0,
  duration: 25,
  ease: [0, 0, 1, 1],
  type: "tween",
};
const animation = { opacity: 1, rotate: 360, scale: 1, x: 0, y: 0 };
const transition2 = {
  delay: 0,
  duration: 8,
  ease: [0, 0, 1, 1],
  type: "tween",
};
const animation1 = { opacity: 1, rotate: -360, scale: 1, x: 0, y: 0 };
const transformTemplate = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) =>
  variants.join("-") + props.layoutDependency;
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    gestureVariant,
    setGestureState,
    setVariant,
    transition,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "sBbVTkEzY",
    transitions,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Transition, {
      value: transition,
      children: /*#__PURE__*/ _jsxs(motion.div, {
        ...restProps,
        animate: variants,
        className: cx(
          serializationHash,
          ...sharedStyleClassNames,
          "framer-162cfys",
          className,
          classNames,
        ),
        "data-framer-name": "InProgress",
        initial: variant,
        layoutDependency: layoutDependency,
        layoutId: "sBbVTkEzY",
        onHoverEnd: () => setGestureState({ isHovered: false }),
        onHoverStart: () => setGestureState({ isHovered: true }),
        onTap: () => setGestureState({ isPressed: false }),
        onTapCancel: () => setGestureState({ isPressed: false }),
        onTapStart: () => setGestureState({ isPressed: true }),
        ref: ref !== null && ref !== void 0 ? ref : ref1,
        style: {
          backgroundColor:
            "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
          borderBottomLeftRadius: 100,
          borderBottomRightRadius: 100,
          borderTopLeftRadius: 100,
          borderTopRightRadius: 100,
          ...style,
        },
        children: [
          /*#__PURE__*/ _jsx(MotionDivWithFX, {
            __framer__loop: animation,
            __framer__loopEffectEnabled: true,
            __framer__loopRepeatDelay: 0,
            __framer__loopRepeatType: "loop",
            __framer__loopTransition: transition1,
            __perspectiveFX: false,
            __smartComponentFX: true,
            __targetOpacity: 1,
            className: "framer-1rz1waw-container",
            "data-framer-name": "InProgress",
            layoutDependency: layoutDependency,
            layoutId: "bigjQiF6A-container",
            name: "InProgress",
            children: /*#__PURE__*/ _jsx(Arc, {
              alignmentBaseline: "bottom",
              animate: false,
              animateDuration: 5,
              animateEnd: 150,
              animateStart: -50,
              color:
                'var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0)) /* {"name":"Black 100"} */',
              cylinderHeight: 0,
              flip: true,
              font: {
                fontFamily: '"Satoshi", "Satoshi Placeholder", sans-serif',
                fontSize: "24px",
                fontStyle: "normal",
                fontWeight: 700,
                letterSpacing: "0.01em",
                lineHeight: "1em",
              },
              height: "100%",
              id: "bigjQiF6A",
              layoutId: "bigjQiF6A",
              name: "InProgress",
              rotate: true,
              rotateSpeed: 2,
              slots: [],
              startOffset: 0,
              style: { height: "100%", width: "100%" },
              text: "● ONGOING ● ONGOING",
              type: "circle",
              width: "100%",
              wordSpacing: 0,
            }),
          }),
          /*#__PURE__*/ _jsx(MotionDivWithFX, {
            __framer__loop: animation1,
            __framer__loopEffectEnabled: true,
            __framer__loopRepeatDelay: 0,
            __framer__loopRepeatType: "loop",
            __framer__loopTransition: transition2,
            __perspectiveFX: false,
            __smartComponentFX: true,
            __targetOpacity: 1,
            className: "framer-v68usu",
            "data-framer-name": "Center",
            layoutDependency: layoutDependency,
            layoutId: "iFkpTAQNc",
            style: {
              borderBottomLeftRadius: 30,
              borderBottomRightRadius: 30,
              borderTopLeftRadius: 30,
              borderTopRightRadius: 30,
            },
            transformTemplate: transformTemplate,
            children: /*#__PURE__*/ _jsx(SVG, {
              className: "framer-1bsmh8a",
              "data-framer-name": "graphic",
              layout: "position",
              layoutDependency: layoutDependency,
              layoutId: "zHKa0wGEO",
              opacity: 1,
              svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 56 56"><path d="M 23.5 7.983 C 26.285 6.375 29.715 6.375 32.5 7.983 L 43.085 14.094 C 45.87 15.702 47.585 18.673 47.585 21.888 L 47.585 34.112 C 47.585 37.327 45.87 40.298 43.085 41.906 L 32.5 48.017 C 29.715 49.625 26.285 49.625 23.5 48.017 L 12.915 41.906 C 10.13 40.298 8.415 37.327 8.415 34.112 L 8.415 21.888 C 8.415 18.673 10.13 15.702 12.915 14.094 Z M 25.846 36.612 C 25.846 37.209 26.33 37.692 26.926 37.692 L 29.074 37.692 C 29.67 37.692 30.154 37.209 30.154 36.612 L 30.154 19.388 C 30.154 18.791 29.67 18.308 29.074 18.308 L 26.926 18.308 C 26.33 18.308 25.846 18.791 25.846 19.388 Z" fill="var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0)) /* {&quot;name&quot;:&quot;Black 100&quot;} */"></path></svg>',
              svgContentId: 2352495373,
              withExternalLayout: true,
            }),
          }),
        ],
      }),
    }),
  });
});
const css = [
  '.framer-vmej5[data-border="true"]::after, .framer-vmej5 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-vmej5.framer-d69l00, .framer-vmej5 .framer-d69l00 { display: block; }",
  ".framer-vmej5.framer-162cfys { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100px; justify-content: center; overflow: hidden; padding: 10px 20px 10px 20px; position: relative; width: 100px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-vmej5 .framer-1rz1waw-container { aspect-ratio: 1 / 1; flex: none; height: 76%; position: relative; width: var(--framer-aspect-ratio-supported, 61px); z-index: 1; }",
  ".framer-vmej5 .framer-v68usu { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 55px); justify-content: center; left: 50%; overflow: hidden; padding: 0px 0px 0px 0px; position: absolute; top: 50%; width: 55%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  ".framer-vmej5 .framer-1bsmh8a { flex: none; height: 56px; position: relative; width: 56px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vmej5.framer-162cfys, .framer-vmej5 .framer-v68usu { gap: 0px; } .framer-vmej5.framer-162cfys > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-vmej5.framer-162cfys > :first-child { margin-top: 0px; } .framer-vmej5.framer-162cfys > :last-child { margin-bottom: 0px; } .framer-vmej5 .framer-v68usu > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-vmej5 .framer-v68usu > :first-child { margin-left: 0px; } .framer-vmej5 .framer-v68usu > :last-child { margin-right: 0px; } }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 100
 * @framerIntrinsicWidth 100
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 */ const FramersoKmLF9CI = withCSS(Component, css, "framer-vmej5");
export default FramersoKmLF9CI;
FramersoKmLF9CI.displayName = "Home/SealPROGRESS";
FramersoKmLF9CI.defaultProps = { height: 100, width: 100 };
addFonts(FramersoKmLF9CI, [
  {
    family: "Satoshi",
    style: "normal",
    url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
    weight: "700",
  },
  ...ArcFonts,
]);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramersoKmLF9CI",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "100",
        framerIntrinsicHeight: "100",
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./soKmLF9CI.map
