// Generated by Framer (7f988a2)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Effect_MagicHover } from "https://framerusercontent.com/modules/yue1wEIuxL5Wxj17VKpu/rvoe6u8OOiWRrmZZxev9/Toggle.js";
const MotionDivEffect_MagicHover = Effect_MagicHover(motion.div);
const cycleOrder = ["J2J3k_z92", "KuI5DWPh5", "WhsECgdW7"];
const serializationHash = "framer-HjbG1";
const variantClassNames = {
  J2J3k_z92: "framer-v-1ma13e",
  KuI5DWPh5: "framer-v-mvnvs5",
  WhsECgdW7: "framer-v-1t038nw",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 28,
  delay: 0,
  mass: 1,
  stiffness: 170,
  type: "spring",
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
  Hide: "WhsECgdW7",
  Off: "KuI5DWPh5",
  On: "J2J3k_z92",
};
const getProps = ({ close, height, id, tap, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    gnzem_49b: close !== null && close !== void 0 ? close : props.gnzem_49b,
    heeY2JMQ7: tap !== null && tap !== void 0 ? tap : props.heeY2JMQ7,
    variant:
      (_ref =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref !== void 0
        ? _ref
        : "J2J3k_z92",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    heeY2JMQ7,
    gnzem_49b,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    gestureHandlers,
    gestureVariant,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "J2J3k_z92",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapl36420 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (heeY2JMQ7) {
      const res = await heeY2JMQ7(...args);
      if (res === false) return false;
    }
    if (gnzem_49b) {
      const res = await gnzem_49b(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-1ma13e",
            className,
            classNames,
          ),
          "data-framer-name": "On",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "J2J3k_z92",
          onTap: onTapl36420,
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            backdropFilter: "blur(8px)",
            backgroundColor:
              "var(--token-d5b2c715-53d2-46d4-afbc-b28efb0692ca, rgba(232, 232, 232, 0.7))",
            borderBottomLeftRadius: 24,
            borderBottomRightRadius: 24,
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            WebkitBackdropFilter: "blur(8px)",
            ...style,
          },
          variants: {
            KuI5DWPh5: {
              backgroundColor:
                "var(--token-0998aeba-5eb4-400a-87c6-fe3a20398e99, rgba(232, 232, 232, 0))",
            },
            WhsECgdW7: {
              backgroundColor:
                "var(--token-0998aeba-5eb4-400a-87c6-fe3a20398e99, rgba(232, 232, 232, 0))",
            },
          },
          ...addPropertyOverrides(
            {
              KuI5DWPh5: { "data-framer-name": "Off" },
              WhsECgdW7: { "data-framer-name": "Hide" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(MotionDivEffect_MagicHover, {
              className: "framer-polcwk",
              "data-framer-name": "X",
              layoutDependency: layoutDependency,
              layoutId: "mj3GODq7T",
              style: {
                borderBottomLeftRadius: 24,
                borderBottomRightRadius: 24,
                borderTopLeftRadius: 24,
                borderTopRightRadius: 24,
                opacity: 1,
              },
              variants: {
                KuI5DWPh5: { opacity: 0 },
                WhsECgdW7: { opacity: 0 },
              },
              children: /*#__PURE__*/ _jsx(SVG, {
                className: "framer-zuc9th",
                "data-framer-name": "graphic",
                layout: "position",
                layoutDependency: layoutDependency,
                layoutId: "HGSDY0C5D",
                opacity: 1,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 19 5 L 5 19 M 5 5 L 19 19" fill="transparent" stroke-width="1.8" stroke="var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0)) /* {&quot;name&quot;:&quot;Black 100&quot;} */" stroke-linecap="round" stroke-linejoin="round"></path></svg>',
                svgContentId: 12018964311,
                withExternalLayout: true,
                ...addPropertyOverrides(
                  { KuI5DWPh5: { svgContentId: 12321253964 } },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-7d5wrt",
              "data-border": true,
              "data-framer-name": "Question",
              layoutDependency: layoutDependency,
              layoutId: "GcRHwXYyX",
              style: {
                "--border-bottom-width": "1.8px",
                "--border-color":
                  "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                "--border-left-width": "1.8px",
                "--border-right-width": "1.8px",
                "--border-style": "solid",
                "--border-top-width": "1.8px",
                backgroundColor:
                  "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                borderBottomLeftRadius: 8,
                borderBottomRightRadius: 8,
                borderTopLeftRadius: 8,
                borderTopRightRadius: 8,
                opacity: 0,
                scale: 1,
              },
              transformTemplate: transformTemplate1,
              variants: {
                KuI5DWPh5: {
                  "--border-bottom-width": "0px",
                  "--border-left-width": "0px",
                  "--border-right-width": "0px",
                  "--border-top-width": "0px",
                  opacity: 1,
                },
                WhsECgdW7: {
                  "--border-bottom-width": "0px",
                  "--border-left-width": "0px",
                  "--border-right-width": "0px",
                  "--border-top-width": "0px",
                  scale: 0.5,
                },
              },
              ...addPropertyOverrides(
                {
                  KuI5DWPh5: { transformTemplate: undefined },
                  WhsECgdW7: { transformTemplate: undefined },
                },
                baseVariant,
                gestureVariant,
              ),
              children: /*#__PURE__*/ _jsx(SVG, {
                className: "framer-19br964",
                layout: "position",
                layoutDependency: layoutDependency,
                layoutId: "uInuupiZ9",
                opacity: 1,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 6 10"><path d="M 2.987 2 L 2.994 2" fill="transparent" stroke-width="1.8" stroke="var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White 100&quot;} */" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 3 8.667 L 3 5.333" fill="transparent" stroke-width="1.5" stroke="var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White 100&quot;} */" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>',
                svgContentId: 10737003728,
                withExternalLayout: true,
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-HjbG1.framer-1o0ah4v, .framer-HjbG1 .framer-1o0ah4v { display: block; }",
  ".framer-HjbG1.framer-1ma13e { cursor: pointer; height: 42px; overflow: hidden; position: relative; width: 42px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-HjbG1 .framer-polcwk { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
  ".framer-HjbG1 .framer-zuc9th { flex: none; height: 24px; position: relative; width: 24px; }",
  ".framer-HjbG1 .framer-7d5wrt { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); left: 50%; overflow: hidden; pointer-events: none; position: absolute; top: -17px; width: 16px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-HjbG1 .framer-19br964 { flex: none; height: 10px; left: calc(50.00000000000002% - 6px / 2); position: absolute; top: calc(50.00000000000002% - 10px / 2); width: 6px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-HjbG1 .framer-polcwk { gap: 0px; } .framer-HjbG1 .framer-polcwk > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-HjbG1 .framer-polcwk > :first-child { margin-top: 0px; } .framer-HjbG1 .framer-polcwk > :last-child { margin-bottom: 0px; } }",
  ".framer-HjbG1.framer-v-mvnvs5.framer-1ma13e, .framer-HjbG1.framer-v-1t038nw.framer-1ma13e { height: 16px; width: 16px; }",
  ".framer-HjbG1.framer-v-mvnvs5 .framer-polcwk, .framer-HjbG1.framer-v-1t038nw .framer-polcwk { bottom: -46px; top: 46px; }",
  ".framer-HjbG1.framer-v-mvnvs5 .framer-7d5wrt, .framer-HjbG1.framer-v-1t038nw .framer-7d5wrt { left: 0px; right: 0px; top: 0px; width: unset; }",
  '.framer-HjbG1[data-border="true"]::after, .framer-HjbG1 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 42
 * @framerIntrinsicWidth 42
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"KuI5DWPh5":{"layout":["fixed","fixed"]},"WhsECgdW7":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"heeY2JMQ7":"tap","gnzem_49b":"close"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerVPFSIhH7_ = withCSS(Component, css, "framer-HjbG1");
export default FramerVPFSIhH7_;
FramerVPFSIhH7_.displayName = "Toggle/Close";
FramerVPFSIhH7_.defaultProps = { height: 42, width: 42 };
addPropertyControls(FramerVPFSIhH7_, {
  variant: {
    options: ["J2J3k_z92", "KuI5DWPh5", "WhsECgdW7"],
    optionTitles: ["On", "Off", "Hide"],
    title: "Variant",
    type: ControlType.Enum,
  },
  heeY2JMQ7: { title: "Tap", type: ControlType.EventHandler },
  gnzem_49b: { title: "Close", type: ControlType.EventHandler },
});
addFonts(FramerVPFSIhH7_, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerVPFSIhH7_",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "42",
        framerIntrinsicHeight: "42",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerVariables: '{"heeY2JMQ7":"tap","gnzem_49b":"close"}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"KuI5DWPh5":{"layout":["fixed","fixed"]},"WhsECgdW7":{"layout":["fixed","fixed"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
