// Generated by Framer (6b748fa)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import {
  Language_Chn_Content,
  Language_En_Content,
} from "https://framerusercontent.com/modules/yue1wEIuxL5Wxj17VKpu/rvoe6u8OOiWRrmZZxev9/Toggle.js";
import * as sharedStyle from "https://framerusercontent.com/modules/IJuPkH75DrOaXa8hMB2D/uNPycaMZJ1T8jriUTsGK/sSyE5_N0_.js";
import UtilitiesScrollAssistant from "https://framerusercontent.com/modules/4z2cCPFuRdAyEFutOkNd/dBEmOjddrcXGtvBa2Zr3/FBSb6VN4C.js";
import ToggleClose from "https://framerusercontent.com/modules/l8dPDk7flAoGIG0iln8T/xIMISI5vAhekjBEhgFlr/VPFSIhH7_.js";
const ToggleCloseFonts = getFonts(ToggleClose);
const UtilitiesScrollAssistantFonts = getFonts(UtilitiesScrollAssistant);
const RichTextLanguage_En_Content = Language_En_Content(RichText);
const RichTextLanguage_Chn_Content = Language_Chn_Content(RichText);
const cycleOrder = ["ZuBY0N3FQ", "qiYYLD700"];
const serializationHash = "framer-U6LWb";
const variantClassNames = {
  qiYYLD700: "framer-v-15qf2cx",
  ZuBY0N3FQ: "framer-v-itodxn",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 28,
  delay: 0,
  mass: 1,
  stiffness: 170,
  type: "spring",
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
  Collasped: "qiYYLD700",
  Expanded: "ZuBY0N3FQ",
};
const getProps = ({ close, height, id, open, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    d6MkcFD8T: close !== null && close !== void 0 ? close : props.d6MkcFD8T,
    kEaKLjxdV: open !== null && open !== void 0 ? open : props.kEaKLjxdV,
    variant:
      (_ref =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref !== void 0
        ? _ref
        : "ZuBY0N3FQ",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    kEaKLjxdV,
    d6MkcFD8T,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "ZuBY0N3FQ",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const heeY2JMQ7pp3zzc = activeVariantCallback(async (...args) => {
    if (d6MkcFD8T) {
      const res = await d6MkcFD8T(...args);
      if (res === false) return false;
    }
  });
  const onTap16osazx = activeVariantCallback(async (...args) => {
    if (kEaKLjxdV) {
      const res = await kEaKLjxdV(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [sharedStyle.className];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-itodxn",
            className,
            classNames,
          ),
          "data-framer-name": "Expanded",
          layoutDependency: layoutDependency,
          layoutId: "ZuBY0N3FQ",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style },
          ...addPropertyOverrides(
            { qiYYLD700: { "data-framer-name": "Collasped" } },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-ybl0gi-container",
                layoutDependency: layoutDependency,
                layoutId: "Wtd9D4iqM-container",
                style: { opacity: 1, scale: 1 },
                transformTemplate: transformTemplate1,
                variants: { qiYYLD700: { opacity: 0, scale: 0.4 } },
                children: /*#__PURE__*/ _jsx(ToggleClose, {
                  heeY2JMQ7: heeY2JMQ7pp3zzc,
                  height: "100%",
                  id: "Wtd9D4iqM",
                  layoutId: "Wtd9D4iqM",
                  variant: "J2J3k_z92",
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-109uxv3",
              "data-framer-name": "Space",
              "data-highlight": true,
              layoutDependency: layoutDependency,
              layoutId: "ZgMUIKzuk",
              onTap: onTap16osazx,
              style: {
                borderBottomLeftRadius: 24,
                borderBottomRightRadius: 24,
                borderTopLeftRadius: 24,
                borderTopRightRadius: 24,
              },
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1pyz0qx",
                "data-framer-name": "Content",
                layoutDependency: layoutDependency,
                layoutId: "GYVZD2n69",
                style: {
                  backgroundColor:
                    "var(--token-50dd0df5-e960-4a6c-8af2-3b7603ba51c8, rgba(0, 0, 0, 0))",
                },
                transformTemplate: transformTemplate2,
                variants: {
                  qiYYLD700: {
                    backgroundColor:
                      "var(--token-46294d69-7c7f-4036-8b2c-a3ef80ae1f58, rgb(0, 0, 0))",
                  },
                },
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1sji601",
                    layoutDependency: layoutDependency,
                    layoutId: "kUph1Kh9V",
                    style: {
                      backgroundColor:
                        "var(--token-d5b2c715-53d2-46d4-afbc-b28efb0692ca, rgba(232, 232, 232, 0.7))",
                      borderBottomLeftRadius: 24,
                      borderBottomRightRadius: 24,
                      borderTopLeftRadius: 24,
                      borderTopRightRadius: 24,
                    },
                    variants: {
                      qiYYLD700: {
                        backgroundColor:
                          "var(--token-0998aeba-5eb4-400a-87c6-fe3a20398e99, rgba(232, 232, 232, 0))",
                      },
                    },
                    children: [
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1wauial",
                        "data-framer-name": "Animation",
                        layoutDependency: layoutDependency,
                        layoutId: "GCW2kzps9",
                        style: {
                          backgroundColor:
                            "var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255))",
                          borderBottomLeftRadius: 16,
                          borderBottomRightRadius: 16,
                          borderTopLeftRadius: 16,
                          borderTopRightRadius: 16,
                          opacity: 1,
                        },
                        variants: { qiYYLD700: { opacity: 0 } },
                        children: /*#__PURE__*/ _jsx(
                          ComponentViewportProvider,
                          {
                            width: "286px",
                            children: /*#__PURE__*/ _jsx(motion.div, {
                              className: "framer-126y4la-container",
                              layoutDependency: layoutDependency,
                              layoutId: "B3U37AjtO-container",
                              children: /*#__PURE__*/ _jsx(
                                UtilitiesScrollAssistant,
                                {
                                  height: "100%",
                                  id: "B3U37AjtO",
                                  layoutId: "B3U37AjtO",
                                  style: { height: "100%", width: "100%" },
                                  variant: "aMllQyYGb",
                                  width: "100%",
                                  ...addPropertyOverrides(
                                    { qiYYLD700: { variant: "wuXOcDovs" } },
                                    baseVariant,
                                    gestureVariant,
                                  ),
                                },
                              ),
                            }),
                          },
                        ),
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-rnaa0b",
                        "data-framer-name": "Description",
                        layoutDependency: layoutDependency,
                        layoutId: "GjqRFOKIa",
                        style: { opacity: 1 },
                        variants: { qiYYLD700: { opacity: 0 } },
                        children: [
                          /*#__PURE__*/ _jsx(RichTextLanguage_En_Content, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-9jlebu",
                                "data-styles-preset": "sSyE5_N0_",
                                children:
                                  "In the cases where you don't have a touch device, use the mouse wheel to control the stack.",
                              }),
                            }),
                            className: "framer-ychzne",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "ysKHWzJ8x",
                            style: {
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(RichTextLanguage_Chn_Content, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-9jlebu",
                                "data-styles-preset": "sSyE5_N0_",
                                children:
                                  "在不使用触摸设备的情况下，启用鼠标滚轮来控制水平滚动。",
                              }),
                            }),
                            className: "framer-19uykqd",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "m_Pr6EZFH",
                            style: {
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-19ladts",
                    "data-framer-name": "Info",
                    layoutDependency: layoutDependency,
                    layoutId: "jIQ09QLTh",
                    style: {
                      borderBottomLeftRadius: 8,
                      borderBottomRightRadius: 8,
                      borderTopLeftRadius: 8,
                      borderTopRightRadius: 8,
                      opacity: 0,
                      scale: 4,
                    },
                    transformTemplate: transformTemplate2,
                    variants: { qiYYLD700: { opacity: 1, scale: 1 } },
                    children: /*#__PURE__*/ _jsx(SVG, {
                      className: "framer-w2imfx",
                      layout: "position",
                      layoutDependency: layoutDependency,
                      layoutId: "Y82oAtoCy",
                      opacity: 1,
                      svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 6 10"><path d="M 2.987 2 L 2.994 2" fill="transparent" stroke-width="1.8" stroke="var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White 100&quot;} */" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 3 8.667 L 3 5.333" fill="transparent" stroke-width="1.5" stroke="var(--token-c2d1fabf-b433-4a44-8215-ec448220e490, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White 100&quot;} */" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>',
                      svgContentId: 10737003728,
                      withExternalLayout: true,
                    }),
                  }),
                ],
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-U6LWb.framer-ysklkh, .framer-U6LWb .framer-ysklkh { display: block; }",
  ".framer-U6LWb.framer-itodxn { height: 300px; overflow: visible; position: relative; width: 302px; }",
  ".framer-U6LWb .framer-ybl0gi-container { bottom: -62px; flex: none; height: auto; left: 50%; pointer-events: auto; position: absolute; width: auto; }",
  ".framer-U6LWb .framer-109uxv3 { bottom: 0px; cursor: pointer; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-U6LWb .framer-1pyz0qx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; position: absolute; top: 50%; width: 302px; }",
  ".framer-U6LWb .framer-1sji601 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 300px; justify-content: center; overflow: hidden; padding: 8px 8px 12px 8px; position: relative; width: 302px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-U6LWb .framer-1wauial { aspect-ratio: 1.3333333333333333 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 150px); overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-U6LWb .framer-126y4la-container { bottom: 1px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
  ".framer-U6LWb .framer-rnaa0b { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 58px; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 10px; position: relative; width: 100%; }",
  ".framer-U6LWb .framer-ychzne, .framer-U6LWb .framer-19uykqd { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-U6LWb .framer-19ladts { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); left: 50%; overflow: hidden; pointer-events: none; position: absolute; top: 50%; width: 16px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  ".framer-U6LWb .framer-w2imfx { flex: none; height: 10px; left: calc(50.00000000000002% - 6px / 2); position: absolute; top: calc(50.00000000000002% - 10px / 2); width: 6px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-U6LWb .framer-1pyz0qx, .framer-U6LWb .framer-1sji601, .framer-U6LWb .framer-rnaa0b { gap: 0px; } .framer-U6LWb .framer-1pyz0qx > *, .framer-U6LWb .framer-1sji601 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-U6LWb .framer-1pyz0qx > :first-child, .framer-U6LWb .framer-1sji601 > :first-child, .framer-U6LWb .framer-rnaa0b > :first-child { margin-top: 0px; } .framer-U6LWb .framer-1pyz0qx > :last-child, .framer-U6LWb .framer-1sji601 > :last-child, .framer-U6LWb .framer-rnaa0b > :last-child { margin-bottom: 0px; } .framer-U6LWb .framer-rnaa0b > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
  ".framer-U6LWb.framer-v-15qf2cx.framer-itodxn { height: 20px; overflow: hidden; width: 20px; }",
  ".framer-U6LWb.framer-v-15qf2cx .framer-ybl0gi-container { bottom: -51px; }",
  ".framer-U6LWb.framer-v-15qf2cx .framer-109uxv3 { bottom: 2px; left: 2px; right: 2px; top: 2px; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 300
 * @framerIntrinsicWidth 302
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"qiYYLD700":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"kEaKLjxdV":"open","d6MkcFD8T":"close"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerXmmnHeSMP = withCSS(Component, css, "framer-U6LWb");
export default FramerXmmnHeSMP;
FramerXmmnHeSMP.displayName = "Utilities/PopupWheel";
FramerXmmnHeSMP.defaultProps = { height: 300, width: 302 };
addPropertyControls(FramerXmmnHeSMP, {
  variant: {
    options: ["ZuBY0N3FQ", "qiYYLD700"],
    optionTitles: ["Expanded", "Collasped"],
    title: "Variant",
    type: ControlType.Enum,
  },
  kEaKLjxdV: { title: "Open", type: ControlType.EventHandler },
  d6MkcFD8T: { title: "Close", type: ControlType.EventHandler },
});
addFonts(
  FramerXmmnHeSMP,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
          weight: "400",
        },
      ],
    },
    ...ToggleCloseFonts,
    ...UtilitiesScrollAssistantFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerXmmnHeSMP",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "300",
        framerIntrinsicWidth: "302",
        framerImmutableVariables: "true",
        framerVariables: '{"kEaKLjxdV":"open","d6MkcFD8T":"close"}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"qiYYLD700":{"layout":["fixed","fixed"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
