// Generated by Framer (7f988a2)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withMappedReactProps,
} from "../framer_scripts/framer.K3G2LCX5.mjs";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Layout_Variants_Mobile } from "https://framerusercontent.com/modules/RGCgkyyKvYCOcpgTFJih/l8apYUQ1NMMBi28Mu8sO/Page.js";
import HomeLayoutPhone, * as HomeLayoutPhoneInfo from "https://framerusercontent.com/modules/EO0qk94v6XKFgEZKHG6J/4k9phG3ofm40Zc7vjYM4/PpouRypIR.js";
const HomeLayoutPhoneFonts = getFonts(HomeLayoutPhone);
const HomeLayoutPhoneLayout_Variants_MobileWithMappedReactPropsnugwck =
  withMappedReactProps(
    Layout_Variants_Mobile(HomeLayoutPhone),
    HomeLayoutPhoneInfo,
  );
const cycleOrder = ["tKghdUEtj"];
const serializationHash = "framer-D7A19";
const variantClassNames = { tKghdUEtj: "framer-v-1h6j0eo" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion(React.Fragment);
const getProps = ({
  height,
  iconCursor,
  id,
  notice,
  projectCursor,
  width,
  ...props
}) => {
  return {
    ...props,
    pRnzzx5xV:
      iconCursor !== null && iconCursor !== void 0
        ? iconCursor
        : props.pRnzzx5xV,
    XnEXOPyGv:
      projectCursor !== null && projectCursor !== void 0
        ? projectCursor
        : props.XnEXOPyGv,
    YLDaAyo77: notice !== null && notice !== void 0 ? notice : props.YLDaAyo77,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    XnEXOPyGv,
    pRnzzx5xV,
    YLDaAyo77,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    gestureHandlers,
    gestureVariant,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "tKghdUEtj",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const J6eOx28iqz52vxl = activeVariantCallback(async (...args) => {
    if (YLDaAyo77) {
      const res = await YLDaAyo77(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-1h6j0eo",
            className,
            classNames,
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "tKghdUEtj",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            width:
              (componentViewport === null || componentViewport === void 0
                ? void 0
                : componentViewport.width) || "100vw",
            children: /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1qexyga-container",
              layoutDependency: layoutDependency,
              layoutId: "Zh_6F8jUh-container",
              children: /*#__PURE__*/ _jsx(
                HomeLayoutPhoneLayout_Variants_MobileWithMappedReactPropsnugwck,
                {
                  d95Uyy9vG: pRnzzx5xV,
                  height: "100%",
                  id: "Zh_6F8jUh",
                  J6eOx28iq: J6eOx28iqz52vxl,
                  layoutId: "Zh_6F8jUh",
                  lxzOuQJFn: XnEXOPyGv,
                  style: { width: "100%" },
                  variant: "LSoNEMdIJ",
                  width: "100%",
                },
              ),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-D7A19.framer-1hwcl5x, .framer-D7A19 .framer-1hwcl5x { display: block; }",
  ".framer-D7A19.framer-1h6j0eo { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 390px; }",
  ".framer-D7A19 .framer-1qexyga-container { flex: none; height: auto; position: relative; width: 100%; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-D7A19.framer-1h6j0eo { gap: 0px; } .framer-D7A19.framer-1h6j0eo > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-D7A19.framer-1h6j0eo > :first-child { margin-top: 0px; } .framer-D7A19.framer-1h6j0eo > :last-child { margin-bottom: 0px; } }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 6338
 * @framerIntrinsicWidth 390
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"XnEXOPyGv":"projectCursor","pRnzzx5xV":"iconCursor","YLDaAyo77":"notice"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerzNfJs9xcz = withCSS(Component, css, "framer-D7A19");
export default FramerzNfJs9xcz;
FramerzNfJs9xcz.displayName = "Home/HeroPhone";
FramerzNfJs9xcz.defaultProps = { height: 6338, width: 390 };
addPropertyControls(FramerzNfJs9xcz, {
  XnEXOPyGv: { title: "Project Cursor", type: ControlType.CustomCursor },
  pRnzzx5xV: { title: "Icon Cursor", type: ControlType.CustomCursor },
  YLDaAyo77: { title: "Notice", type: ControlType.EventHandler },
});
addFonts(
  FramerzNfJs9xcz,
  [{ explicitInter: true, fonts: [] }, ...HomeLayoutPhoneFonts],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerzNfJs9xcz",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "6338",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "390",
        framerVariables:
          '{"XnEXOPyGv":"projectCursor","pRnzzx5xV":"iconCursor","YLDaAyo77":"notice"}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
